version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: "[npm] Dependabot:"
      prefix-development: "[npm-dev] Dependabot:"
    pull-request-branch-name:
      separator: "-"