import { ActivityDto } from '@app/shared/api/services/IActivityService';

export const abTrailsInput: ActivityDto = {
  id: '64e32047-22d8-1858-d681-b9d600000000',
  name: 'Trails_Mobile',
  description: 'A/B Trails',
  splashScreen: 'splash',
  image: '',
  showAllAtOnce: false,
  isSkippable: false,
  isReviewable: false,
  isHidden: false,
  autoAssign: true,
  responseIsEditable: true,
  order: 2,
  items: [
    {
      question: 'Sample A',
      responseType: 'ABTrails',
      responseValues: null,
      config: {
        deviceType: 'mobile',
        tutorials: {
          tutorials: [
            {
              text: 'There are numbers in circles on this screen.',
              nodeLabel: '',
            },
            {
              text: 'You will take a pen and draw a line from one number to the next, in order.',
              nodeLabel: '',
            },
            { text: 'Start at 1.', nodeLabel: '1' },
            { text: 'Then go to 2.', nodeLabel: '2' },
            { text: 'Then 3, and so on.', nodeLabel: '3' },
            {
              text: 'Please try not to lift the pen as you move from one number to the next. Work as quickly as you can.',
              nodeLabel: '',
            },
            { text: 'Begin here.', nodeLabel: '1' },
            { text: 'And end here.', nodeLabel: '11' },
            { text: 'Click next to start', nodeLabel: '' },
          ],
        },
        nodes: {
          radius: 4.18,
          fontSize: 5.6,
          fontSizeBeginEnd: null,
          beginWordLength: null,
          endWordLength: null,
          nodes: [
            { orderIndex: 1, cx: 52.24, cy: 11.94, label: '1' },
            { orderIndex: 2, cx: 85.07, cy: 17.91, label: '2' },
            { orderIndex: 3, cx: 88.06, cy: 74.63, label: '3' },
            { orderIndex: 4, cx: 53.73, cy: 86.57, label: '4' },
            { orderIndex: 5, cx: 77.61, cy: 40.3, label: '5' },
            { orderIndex: 6, cx: 17.01, cy: 38.81, label: '6' },
            { orderIndex: 7, cx: 53.73, cy: 56.72, label: '7' },
            { orderIndex: 8, cx: 19.4, cy: 79.1, label: '8' },
            { orderIndex: 9, cx: 14.93, cy: 59.7, label: '9' },
            { orderIndex: 10, cx: 50.75, cy: 31.34, label: '10' },
            { orderIndex: 11, cx: 13.43, cy: 14.93, label: '11' },
          ],
        },
      },
      name: 'trail1',
      isHidden: false,
      conditionalLogic: null,
      id: '64e3204b-22d8-1858-d681-b9e000000000',
      order: 1,
      timer: null,
    },
    {
      question: 'Test A',
      responseType: 'ABTrails',
      responseValues: null,
      config: {
        deviceType: 'mobile',
        tutorials: {
          tutorials: [
            {
              text: 'On this screen are more numbers in circles.',
              nodeLabel: '',
            },
            {
              text: 'You will take a pen and draw a line from one circle to the next, in order.',
              nodeLabel: '',
            },
            { text: 'Start at 1.', nodeLabel: '1' },
            { text: 'And End here.', nodeLabel: '11' },
            {
              text: 'Please try not to lift the pen as you move from one circle to the next.',
              nodeLabel: '',
            },
            { text: 'Work as quickly as you can.', nodeLabel: '' },
            { text: 'Click next to start', nodeLabel: '' },
          ],
        },
        nodes: {
          radius: 4.18,
          fontSize: 5.97,
          fontSizeBeginEnd: null,
          beginWordLength: null,
          endWordLength: null,
          nodes: [
            { orderIndex: 1, cx: 17.01, cy: 38.81, label: '1' },
            { orderIndex: 2, cx: 77.61, cy: 40.3, label: '2' },
            { orderIndex: 3, cx: 52.24, cy: 11.94, label: '3' },
            { orderIndex: 4, cx: 13.43, cy: 14.93, label: '4' },
            { orderIndex: 5, cx: 53.73, cy: 56.72, label: '5' },
            { orderIndex: 6, cx: 85.07, cy: 17.91, label: '6' },
            { orderIndex: 7, cx: 88.06, cy: 74.63, label: '7' },
            { orderIndex: 8, cx: 14.93, cy: 59.7, label: '8' },
            { orderIndex: 9, cx: 19.4, cy: 79.1, label: '9' },
            { orderIndex: 10, cx: 50.75, cy: 31.34, label: '10' },
            { orderIndex: 11, cx: 53.73, cy: 86.57, label: '11' },
          ],
        },
      },
      name: 'trail2',
      isHidden: false,
      conditionalLogic: null,
      id: '64e3204c-22d8-1858-d681-b9e100000000',

      order: 1,
      timer: null,
    },
    {
      question: 'Sample B',
      responseType: 'ABTrails',
      responseValues: null,
      config: {
        deviceType: 'mobile',
        tutorials: {
          tutorials: [
            {
              text: 'There are numbers and letters in circles on this screen.',
              nodeLabel: '',
            },
            {
              text: 'You will take a pen and draw a line alternating in order between the numbers and letters.',
              nodeLabel: '',
            },
            { text: 'Start at number 1.', nodeLabel: '1' },
            { text: 'Then go to the first letter A.', nodeLabel: 'A' },
            { text: 'Then go to the next number 2.', nodeLabel: '2' },
            {
              text: 'Then go to the next letter B, and so on.',
              nodeLabel: 'B',
            },
            {
              text: 'Please try not to lift the pen as you move from one number to the next. Work as quickly as you can.',
              nodeLabel: '',
            },
            { text: 'Begin here.', nodeLabel: '1' },
            { text: 'And end here.', nodeLabel: '6' },
            { text: 'Click next to start', nodeLabel: '' },
          ],
        },
        nodes: {
          radius: 4.18,
          fontSize: 5.97,
          fontSizeBeginEnd: null,
          beginWordLength: null,
          endWordLength: null,
          nodes: [
            { orderIndex: 1, cx: 53.73, cy: 86.57, label: '1' },
            { orderIndex: 2, cx: 88.06, cy: 74.63, label: 'A' },
            { orderIndex: 3, cx: 85.07, cy: 17.91, label: '2' },
            { orderIndex: 4, cx: 52.24, cy: 11.94, label: 'B' },
            { orderIndex: 5, cx: 77.61, cy: 40.3, label: '3' },
            { orderIndex: 6, cx: 14.92, cy: 59.7, label: 'C' },
            { orderIndex: 7, cx: 50.75, cy: 31.34, label: '4' },
            { orderIndex: 8, cx: 13.43, cy: 14.92, label: 'D' },
            { orderIndex: 9, cx: 53.73, cy: 56.72, label: '5' },
            { orderIndex: 10, cx: 17.01, cy: 38.81, label: 'E' },
            { orderIndex: 11, cx: 19.4, cy: 79.1, label: '6' },
          ],
        },
      },
      name: 'trail3',
      isHidden: false,
      conditionalLogic: null,
      id: '64e3204d-22d8-1858-d681-b9e200000000',

      order: 1,
      timer: null,
    },
    {
      question: 'Test B',
      responseType: 'ABTrails',
      responseValues: null,
      config: {
        deviceType: 'mobile',
        tutorials: {
          tutorials: [
            {
              text: 'On this screen there are more numbers and letters in circles.',
              nodeLabel: '',
            },
            {
              text: 'You will take a pen and draw a line from one circle to the next.',
              nodeLabel: '',
            },
            {
              text: 'Alternating in order between the numbers and letters.',
              nodeLabel: '',
            },
            { text: 'Start at 1.', nodeLabel: '1' },
            { text: 'And end here.', nodeLabel: '6' },
            {
              text: 'Please try not to lift the pen as you move from one circle to the next.',
              nodeLabel: '',
            },
            { text: 'Work as quickly as you can.', nodeLabel: '' },
            { text: 'Click next to start', nodeLabel: '' },
          ],
        },
        nodes: {
          radius: 4.18,
          fontSize: 5.97,
          fontSizeBeginEnd: null,
          beginWordLength: null,
          endWordLength: null,
          nodes: [
            { orderIndex: 1, cx: 50.75, cy: 31.34, label: '1' },
            { orderIndex: 2, cx: 13.43, cy: 14.93, label: 'A' },
            { orderIndex: 3, cx: 52.24, cy: 11.94, label: '2' },
            { orderIndex: 4, cx: 17.01, cy: 38.81, label: 'B' },
            { orderIndex: 5, cx: 77.61, cy: 40.3, label: '3' },
            { orderIndex: 6, cx: 85.07, cy: 17.91, label: 'C' },
            { orderIndex: 7, cx: 88.06, cy: 74.63, label: '4' },
            { orderIndex: 8, cx: 14.93, cy: 59.7, label: 'D' },
            { orderIndex: 9, cx: 53.73, cy: 56.72, label: '5' },
            { orderIndex: 10, cx: 19.4, cy: 79.1, label: 'E' },
            { orderIndex: 11, cx: 53.73, cy: 86.57, label: '6' },
          ],
        },
      },
      name: 'trail4',
      isHidden: false,
      conditionalLogic: null,
      id: '64e3204e-22d8-1858-d681-b9e300000000',

      order: 1,
      timer: null,
    },
  ],
  scoresAndReports: {
    showScoreSummary: false,
    reports: [],
  },
};

export const cstInput: ActivityDto = {
  id: '64e32047-22d8-1858-d681-b9da00000000',
  name: 'Stability_Task_gyro (custom)',
  description: 'This activity contains Stability tracker item.',
  splashScreen: '',
  image: '',
  showAllAtOnce: false,
  isSkippable: false,
  isReviewable: false,
  isHidden: false,
  autoAssign: true,
  responseIsEditable: true,
  order: 6,
  items: [
    {
      order: 1,
      timer: null,
      question:
        '# Hello!\nIn this task, you will see a disc that will drift either to the left or right side of the screen.\n Your job will be to keep the disc in the middle of the screen.\n If the disc is moving to the right, tilt your phone to the left to bring it back to the center.\n If the disc is moving to the left, tilt your phone to the right to bring the disc back to center.\n Do not let the disc touch the walls to the far left or right of the screen.\n There will be two phases to this task, a Challenge Phase, and a Focus Phase.',
      responseType: 'message',
      responseValues: null,
      config: { removeBackButton: false, timer: null },
      name: 'instructions',
      isHidden: false,
      conditionalLogic: null,
      id: '64e32059-22d8-1858-d681-ba0300000000',
    },
    {
      order: 2,
      timer: null,
      question:
        'This is the Challenge Phase.\n There will be 2 trials.\n Each trial will begin at an easy level, but it will become more difficult to keep the disc at the center of the screen.\n Eventually, you will lose control of the disc.\n When it hits a wall at the edge of the screen, the trial ends and the disc will be moved back to the center of the screen.\n Try to keep the disc away from the walls for as long as possible on each trial.',
      responseType: 'message',
      responseValues: null,
      config: { removeBackButton: false, timer: null },
      name: 'calibration-instructions',
      isHidden: false,
      conditionalLogic: null,
      id: '64e32059-22d8-1858-d681-ba0400000000',
    },
    {
      order: 3,
      timer: null,
      question: '',
      responseType: 'stabilityTracker',
      responseValues: null,
      config: {
        userInputType: 'gyroscope',
        phase: 'practice',
        trialsNumber: 2,
        durationMinutes: 1,
        lambdaSlope: 50,
      },
      name: 'calibration-phase',
      isHidden: false,
      conditionalLogic: null,
      id: '64e3205a-22d8-1858-d681-ba0500000000',
    },
    {
      order: 1,
      timer: null,
      question:
        'This is the Focus Phase.\n This phase will last 1 minutes.\n The trial will begin at an easy level, and will increase to a level that should not be very difficult.\n Your task will be to focus on keeping the disc in the center of the screen, without letting it drift off center.\n If you lose control of the disc and it hits a wall, the disc will be moved back to the center of the screen and the task will continue.',
      responseType: 'message',
      responseValues: null,
      config: { removeBackButton: false, timer: null },
      name: 'continuous-instructions',
      isHidden: false,
      conditionalLogic: null,
      id: '64e3205a-22d8-1858-d681-ba0600000000',
    },
    {
      question: '',
      responseType: 'stabilityTracker',
      responseValues: null,
      config: {
        userInputType: 'gyroscope',
        phase: 'test',
        trialsNumber: 0,
        durationMinutes: 1,
        lambdaSlope: 50,
      },
      name: 'continuous-phase',
      isHidden: false,
      conditionalLogic: null,
      id: '64e3205b-22d8-1858-d681-ba0700000000',
      order: 1,
      timer: null,
    },
  ],
  scoresAndReports: {
    showScoreSummary: false,
    reports: [],
  },
};

export const flankerInput: ActivityDto = {
  id: '64e32047-22d8-1858-d681-b9d700000000',
  name: 'Simple & Choice Reaction Time Task Builder',
  description: '75%; no fixation; randomize',
  splashScreen: '',
  image: '',
  showAllAtOnce: false,
  isSkippable: false,
  isReviewable: false,
  isHidden: false,
  autoAssign: true,
  responseIsEditable: true,
  order: 3,
  items: [
    {
      order: 1,
      timer: null,
      question:
        '## General Instructions\n\n\n You will see arrows presented at the center of the screen that point either to the left ‘<’ or right ‘>’.\n Press the left button if the arrow is pointing to the left ‘<’ or press the right button if the arrow is pointing to the right ‘>’.\n These arrows will appear in the center of a line of other items. Sometimes, these other items will be arrows pointing in the same direction, e.g.. ‘> > > > >’, or in the opposite direction, e.g. ‘< < > < <’.\n Your job is to respond to the central arrow, no matter what direction the other arrows are pointing.\n For example, you would press the left button for both ‘< < < < <’, and ‘> > < > >’ because the middle arrow points to the left.\n Finally, in some trials dashes ‘ - ’ will appear beside the central arrow.\n Again, respond only to the direction of the central arrow. Please respond as quickly and accurately as possible.',
      responseType: 'message',
      responseValues: null,
      config: { removeBackButton: false, timer: null },
      name: 'vsr-instructions',
      isHidden: false,
      conditionalLogic: null,
      id: '64e3204e-22d8-1858-d681-b9e400000000',
    },
    {
      order: 1,
      timer: null,
      question:
        '## Instructions\n\nNow you will have a chance to practice the task before moving on to the test phase.\nRemember to respond only to the central arrow\n',
      responseType: 'message',
      responseValues: null,
      config: { removeBackButton: false, timer: null },
      name: 'practice-instructions',
      isHidden: false,
      conditionalLogic: null,
      id: '64e3204e-22d8-1858-d681-b9e500000000',
    },
    {
      order: 1,
      timer: null,
      question: '',
      responseType: 'flanker',
      responseValues: null,
      config: {
        fixationDuration: 100,
        fixationScreen: {
          value: 'value',
          image: 'url',
        },
        stimulusTrials: [
          {
            id: '5__png0',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/uT9zciGBfB5d7EXu7oyN8g.png',
            text: '5.png',
            value: 0,
            weight: null,
          },
          {
            id: 'image__1__png1',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/2F159Gsy66NdSgrdgsFAXL.png',
            text: 'image 1.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__2__png2',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/swBFCcF4DaGyXEusHY6PQK.png',
            text: 'IMAGE 2.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__png3',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/qgYVs1v9yVcE48B2psKuBP.png',
            text: 'IMAGE.png',
            value: 0,
            weight: null,
          },
          {
            id: 'iMAGE__3__png4',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/o68MKdhg2rJZ4sQG8UoEqL.png',
            text: 'iMAGE_3.png',
            value: 1,
            weight: null,
          },
          {
            id: '____________6__png5',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/tk8KsE56LsMW5vepDQrc5K.png',
            text: 'ШЬФПУ 6.png',
            value: 1,
            weight: null,
          },
        ],
        blocks: [
          {
            name: 'block 1',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 2',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 3',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 4',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
        ],
        buttons: [
          { text: 'HOME', image: null, value: 0 },
          { text: 'WILD', image: null, value: 1 },
        ],
        nextButton: 'OK',
        minimumAccuracy: 75,
        sampleSize: 1,
        samplingMethod: 'randomize-order',
        showFeedback: true,
        showFixation: false,
        showResults: true,
        trialDuration: 3000,
        isLastPractice: false,
        isFirstPractice: false,
        isLastTest: false,
        blockType: 'practice',
      },
      name: 'trial',
      isHidden: false,
      conditionalLogic: null,
      id: '64e3204f-22d8-1858-d681-b9e600000000',
    },
    {
      order: 1,
      timer: null,
      question: '## Instructions\nPress the Next button to restart block.',
      responseType: 'message',
      responseValues: null,
      config: { removeBackButton: false, timer: null },
      name: 'trial2-instructions',
      isHidden: false,
      conditionalLogic: null,
      id: '64e3204f-22d8-1858-d681-b9e700000000',
    },
    {
      order: 1,
      timer: null,
      question: '',
      responseType: 'flanker',
      responseValues: null,
      config: {
        fixationDuration: 2000,
        fixationScreen: {
          value: 'value',
          image: 'url',
        },
        stimulusTrials: [
          {
            id: '5__png0',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/uT9zciGBfB5d7EXu7oyN8g.png',
            text: '5.png',
            value: 0,
            weight: null,
          },
          {
            id: 'image__1__png1',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/2F159Gsy66NdSgrdgsFAXL.png',
            text: 'image 1.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__2__png2',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/swBFCcF4DaGyXEusHY6PQK.png',
            text: 'IMAGE 2.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__png3',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/qgYVs1v9yVcE48B2psKuBP.png',
            text: 'IMAGE.png',
            value: 0,
            weight: null,
          },
          {
            id: 'iMAGE__3__png4',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/o68MKdhg2rJZ4sQG8UoEqL.png',
            text: 'iMAGE_3.png',
            value: 1,
            weight: null,
          },
          {
            id: '____________6__png5',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/tk8KsE56LsMW5vepDQrc5K.png',
            text: 'ШЬФПУ 6.png',
            value: 1,
            weight: null,
          },
        ],
        blocks: [
          {
            name: 'block 1',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 2',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 3',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 4',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
        ],
        buttons: [
          { text: 'HOME', image: null, value: 0 },
          { text: 'WILD', image: null, value: 1 },
        ],
        nextButton: 'OK',
        minimumAccuracy: 75,
        sampleSize: 1,
        samplingMethod: 'randomize-order',
        showFeedback: true,
        showFixation: false,
        showResults: true,
        trialDuration: 3000,
        isLastPractice: false,
        isFirstPractice: false,
        isLastTest: false,
        blockType: 'practice',
      },
      name: 'trial2',
      isHidden: false,
      conditionalLogic: null,
      id: '64e3204f-22d8-1858-d681-b9e800000000',
    },
    {
      order: 2,
      timer: null,
      question: '## Instructions\nPress the Next button to restart block.',
      responseType: 'message',
      responseValues: null,
      config: { removeBackButton: false, timer: null },
      name: 'trial3-instructions',
      isHidden: false,
      conditionalLogic: null,
      id: '64e3204f-22d8-1858-d681-b9e900000000',
    },
    {
      order: 2,
      timer: null,
      question: '',
      responseType: 'flanker',
      responseValues: null,
      config: {
        stimulusTrials: [
          {
            id: '5__png0',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/uT9zciGBfB5d7EXu7oyN8g.png',
            text: '5.png',
            value: 0,
            weight: null,
          },
          {
            id: 'image__1__png1',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/2F159Gsy66NdSgrdgsFAXL.png',
            text: 'image 1.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__2__png2',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/swBFCcF4DaGyXEusHY6PQK.png',
            text: 'IMAGE 2.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__png3',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/qgYVs1v9yVcE48B2psKuBP.png',
            text: 'IMAGE.png',
            value: 0,
            weight: null,
          },
          {
            id: 'iMAGE__3__png4',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/o68MKdhg2rJZ4sQG8UoEqL.png',
            text: 'iMAGE_3.png',
            value: 1,
            weight: null,
          },
          {
            id: '____________6__png5',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/tk8KsE56LsMW5vepDQrc5K.png',
            text: 'ШЬФПУ 6.png',
            value: 1,
            weight: null,
          },
        ],
        blocks: [
          {
            name: 'block 1',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 2',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 3',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 4',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
        ],
        buttons: [
          { text: 'HOME', image: null, value: 0 },
          { text: 'WILD', image: null, value: 1 },
        ],
        nextButton: 'OK',
        fixationDuration: 0,
        fixationScreen: { value: 'one', image: 'url' },
        minimumAccuracy: 75,
        sampleSize: 1,
        samplingMethod: 'randomize-order',
        showFeedback: true,
        showFixation: false,
        showResults: true,
        trialDuration: 3000,
        isLastPractice: true,
        isFirstPractice: false,
        isLastTest: false,
        blockType: 'practice',
      },
      name: 'trial3',
      isHidden: false,
      conditionalLogic: null,
      id: '64e32050-22d8-1858-d681-b9ea00000000',
    },
    {
      order: 1,
      timer: null,
      question:
        '## Test Instructions\n\nGood job on the practice blocks.\nYou can now move on to the test blocks.\nYou will do the same task as in the practice, responding to the direction of the central arrow.\nYou will complete 3 blocks, each about 3-5 minutes long.\nYou will have  a short break in between these blocks\n',
      responseType: 'message',
      responseValues: null,
      config: { removeBackButton: false, timer: null },
      name: 'test-instructions',
      isHidden: false,
      conditionalLogic: null,
      id: '64e32050-22d8-1858-d681-b9eb00000000',
    },
  ],
  scoresAndReports: {
    showScoreSummary: false,
    reports: [],
  },
};
