import { ActivityDetails } from '@entities/activity';
import { ActivityDto } from '@shared/api';

export const abTrailsInput: ActivityDto = {
  id: '64e32047-22d8-1858-d681-b9d600000000',
  name: 'Trails_Mobile',
  description: 'A/B Trails',
  splashScreen: '',
  image: '',
  showAllAtOnce: false,
  isSkippable: false,
  isReviewable: false,
  isHidden: false,
  responseIsEditable: true,
  order: 2,
  items: [
    {
      question: 'Sample A',
      responseType: 'ABTrails',
      responseValues: null,
      config: {
        deviceType: 'mobile',
        tutorials: {
          tutorials: [
            {
              text: 'There are numbers in circles on this screen.',
              nodeLabel: null,
            },
            {
              text: 'You will take a pen and draw a line from one number to the next, in order.',
              nodeLabel: null,
            },
            { text: 'Start at 1.', nodeLabel: '1' },
            { text: 'Then go to 2.', nodeLabel: '2' },
            { text: 'Then 3, and so on.', nodeLabel: '3' },
            {
              text: 'Please try not to lift the pen as you move from one number to the next. Work as quickly as you can.',
              nodeLabel: null,
            },
            { text: 'Begin here.', nodeLabel: '1' },
            { text: 'And end here.', nodeLabel: '11' },
            { text: 'Click next to start', nodeLabel: null },
          ],
        },
        nodes: {
          radius: 4.18,
          fontSize: 5.6,
          fontSizeBeginEnd: null,
          beginWordLength: null,
          endWordLength: null,
          nodes: [
            { orderIndex: 1, cx: 52.24, cy: 11.94, label: '1' },
            { orderIndex: 2, cx: 85.07, cy: 17.91, label: '2' },
            { orderIndex: 3, cx: 88.06, cy: 74.63, label: '3' },
            { orderIndex: 4, cx: 53.73, cy: 86.57, label: '4' },
            { orderIndex: 5, cx: 77.61, cy: 40.3, label: '5' },
            { orderIndex: 6, cx: 17.01, cy: 38.81, label: '6' },
            { orderIndex: 7, cx: 53.73, cy: 56.72, label: '7' },
            { orderIndex: 8, cx: 19.4, cy: 79.1, label: '8' },
            { orderIndex: 9, cx: 14.93, cy: 59.7, label: '9' },
            { orderIndex: 10, cx: 50.75, cy: 31.34, label: '10' },
            { orderIndex: 11, cx: 13.43, cy: 14.93, label: '11' },
          ],
        },
      },
      name: 'trail1',
      isHidden: false,
      conditionalLogic: null,
      id: '64e3204b-22d8-1858-d681-b9e000000000',
      order: 1,
      timer: null,
    },
    {
      question: 'Test A',
      responseType: 'ABTrails',
      responseValues: null,
      config: {
        deviceType: 'mobile',
        tutorials: {
          tutorials: [
            {
              text: 'On this screen are more numbers in circles.',
              nodeLabel: null,
            },
            {
              text: 'You will take a pen and draw a line from one circle to the next, in order.',
              nodeLabel: null,
            },
            { text: 'Start at 1.', nodeLabel: '1' },
            { text: 'And End here.', nodeLabel: '11' },
            {
              text: 'Please try not to lift the pen as you move from one circle to the next.',
              nodeLabel: null,
            },
            { text: 'Work as quickly as you can.', nodeLabel: null },
            { text: 'Click next to start', nodeLabel: null },
          ],
        },
        nodes: {
          radius: 4.18,
          fontSize: 5.97,
          fontSizeBeginEnd: null,
          beginWordLength: null,
          endWordLength: null,
          nodes: [
            { orderIndex: 1, cx: 17.01, cy: 38.81, label: '1' },
            { orderIndex: 2, cx: 77.61, cy: 40.3, label: '2' },
            { orderIndex: 3, cx: 52.24, cy: 11.94, label: '3' },
            { orderIndex: 4, cx: 13.43, cy: 14.93, label: '4' },
            { orderIndex: 5, cx: 53.73, cy: 56.72, label: '5' },
            { orderIndex: 6, cx: 85.07, cy: 17.91, label: '6' },
            { orderIndex: 7, cx: 88.06, cy: 74.63, label: '7' },
            { orderIndex: 8, cx: 14.93, cy: 59.7, label: '8' },
            { orderIndex: 9, cx: 19.4, cy: 79.1, label: '9' },
            { orderIndex: 10, cx: 50.75, cy: 31.34, label: '10' },
            { orderIndex: 11, cx: 53.73, cy: 86.57, label: '11' },
          ],
        },
      },
      name: 'trail2',
      isHidden: false,
      conditionalLogic: null,
      id: '64e3204c-22d8-1858-d681-b9e100000000',

      order: 1,
      timer: null,
    },
    {
      question: 'Sample B',
      responseType: 'ABTrails',
      responseValues: null,
      config: {
        deviceType: 'mobile',
        tutorials: {
          tutorials: [
            {
              text: 'There are numbers and letters in circles on this screen.',
              nodeLabel: null,
            },
            {
              text: 'You will take a pen and draw a line alternating in order between the numbers and letters.',
              nodeLabel: null,
            },
            { text: 'Start at number 1.', nodeLabel: '1' },
            { text: 'Then go to the first letter A.', nodeLabel: 'A' },
            { text: 'Then go to the next number 2.', nodeLabel: '2' },
            {
              text: 'Then go to the next letter B, and so on.',
              nodeLabel: 'B',
            },
            {
              text: 'Please try not to lift the pen as you move from one number to the next. Work as quickly as you can.',
              nodeLabel: null,
            },
            { text: 'Begin here.', nodeLabel: '1' },
            { text: 'And end here.', nodeLabel: '6' },
            { text: 'Click next to start', nodeLabel: null },
          ],
        },
        nodes: {
          radius: 4.18,
          fontSize: 5.97,
          fontSizeBeginEnd: null,
          beginWordLength: null,
          endWordLength: null,
          nodes: [
            { orderIndex: 1, cx: 53.73, cy: 86.57, label: '1' },
            { orderIndex: 2, cx: 88.06, cy: 74.63, label: 'A' },
            { orderIndex: 3, cx: 85.07, cy: 17.91, label: '2' },
            { orderIndex: 4, cx: 52.24, cy: 11.94, label: 'B' },
            { orderIndex: 5, cx: 77.61, cy: 40.3, label: '3' },
            { orderIndex: 6, cx: 14.92, cy: 59.7, label: 'C' },
            { orderIndex: 7, cx: 50.75, cy: 31.34, label: '4' },
            { orderIndex: 8, cx: 13.43, cy: 14.92, label: 'D' },
            { orderIndex: 9, cx: 53.73, cy: 56.72, label: '5' },
            { orderIndex: 10, cx: 17.01, cy: 38.81, label: 'E' },
            { orderIndex: 11, cx: 19.4, cy: 79.1, label: '6' },
          ],
        },
      },
      name: 'trail3',
      isHidden: false,
      conditionalLogic: null,
      id: '64e3204d-22d8-1858-d681-b9e200000000',

      order: 1,
      timer: null,
    },
    {
      question: 'Test B',
      responseType: 'ABTrails',
      responseValues: null,
      config: {
        deviceType: 'mobile',
        tutorials: {
          tutorials: [
            {
              text: 'On this screen there are more numbers and letters in circles.',
              nodeLabel: null,
            },
            {
              text: 'You will take a pen and draw a line from one circle to the next.',
              nodeLabel: null,
            },
            {
              text: 'Alternating in order between the numbers and letters.',
              nodeLabel: null,
            },
            { text: 'Start at 1.', nodeLabel: '1' },
            { text: 'And end here.', nodeLabel: '6' },
            {
              text: 'Please try not to lift the pen as you move from one circle to the next.',
              nodeLabel: null,
            },
            { text: 'Work as quickly as you can.', nodeLabel: null },
            { text: 'Click next to start', nodeLabel: null },
          ],
        },
        nodes: {
          radius: 4.18,
          fontSize: 5.97,
          fontSizeBeginEnd: null,
          beginWordLength: null,
          endWordLength: null,
          nodes: [
            { orderIndex: 1, cx: 50.75, cy: 31.34, label: '1' },
            { orderIndex: 2, cx: 13.43, cy: 14.93, label: 'A' },
            { orderIndex: 3, cx: 52.24, cy: 11.94, label: '2' },
            { orderIndex: 4, cx: 17.01, cy: 38.81, label: 'B' },
            { orderIndex: 5, cx: 77.61, cy: 40.3, label: '3' },
            { orderIndex: 6, cx: 85.07, cy: 17.91, label: 'C' },
            { orderIndex: 7, cx: 88.06, cy: 74.63, label: '4' },
            { orderIndex: 8, cx: 14.93, cy: 59.7, label: 'D' },
            { orderIndex: 9, cx: 53.73, cy: 56.72, label: '5' },
            { orderIndex: 10, cx: 19.4, cy: 79.1, label: 'E' },
            { orderIndex: 11, cx: 53.73, cy: 86.57, label: '6' },
          ],
        },
      },
      name: 'trail4',
      isHidden: false,
      conditionalLogic: null,
      id: '64e3204e-22d8-1858-d681-b9e300000000',

      order: 1,
      timer: null,
    },
  ],
  scoresAndReports: {
    generateReport: false,
    showScoreSummary: false,
    reports: [],
  },
};

export const abTrailsOutput: ActivityDetails = {
  description: 'A/B Trails',
  hasSummary: false,
  id: '64e32047-22d8-1858-d681-b9d600000000',
  image: '',
  isHidden: false,
  isReviewable: false,
  isSkippable: false,
  items: [
    {
      canBeReset: false,
      config: {
        config: {
          beginWordLength: null,
          endWordLength: null,
          fontSize: 5.6,
          fontSizeBeginEnd: null,
          radius: 4.18,
        },
        deviceType: 'mobile',
        nodes: [
          {
            cx: 52.24,
            cy: 11.94,
            label: '1',
            orderIndex: 1,
          },
          {
            cx: 85.07,
            cy: 17.91,
            label: '2',
            orderIndex: 2,
          },
          {
            cx: 88.06,
            cy: 74.63,
            label: '3',
            orderIndex: 3,
          },
          {
            cx: 53.73,
            cy: 86.57,
            label: '4',
            orderIndex: 4,
          },
          {
            cx: 77.61,
            cy: 40.3,
            label: '5',
            orderIndex: 5,
          },
          {
            cx: 17.01,
            cy: 38.81,
            label: '6',
            orderIndex: 6,
          },
          {
            cx: 53.73,
            cy: 56.72,
            label: '7',
            orderIndex: 7,
          },
          {
            cx: 19.4,
            cy: 79.1,
            label: '8',
            orderIndex: 8,
          },
          {
            cx: 14.93,
            cy: 59.7,
            label: '9',
            orderIndex: 9,
          },
          {
            cx: 50.75,
            cy: 31.34,
            label: '10',
            orderIndex: 10,
          },
          {
            cx: 13.43,
            cy: 14.93,
            label: '11',
            orderIndex: 11,
          },
        ],
        tutorials: [
          {
            nodeLabel: null,
            text: 'There are numbers in circles on this screen.',
          },
          {
            nodeLabel: null,
            text: 'You will take a pen and draw a line from one number to the next, in order.',
          },
          {
            nodeLabel: '1',
            text: 'Start at 1.',
          },
          {
            nodeLabel: '2',
            text: 'Then go to 2.',
          },
          {
            nodeLabel: '3',
            text: 'Then 3, and so on.',
          },
          {
            nodeLabel: null,
            text: 'Please try not to lift the pen as you move from one number to the next. Work as quickly as you can.',
          },
          {
            nodeLabel: '1',
            text: 'Begin here.',
          },
          {
            nodeLabel: '11',
            text: 'And end here.',
          },
          {
            nodeLabel: null,
            text: 'Click next to start',
          },
        ],
      },
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e3204b-22d8-1858-d681-b9e000000000',
      inputType: 'AbTrails',
      isAbleToMoveBack: false,
      isHidden: false,
      isSkippable: false,
      name: 'trail1',
      order: 1,
      question: 'Sample A',
      timer: null,
    },
    {
      canBeReset: false,
      config: {
        config: {
          beginWordLength: null,
          endWordLength: null,
          fontSize: 5.97,
          fontSizeBeginEnd: null,
          radius: 4.18,
        },
        deviceType: 'mobile',
        nodes: [
          {
            cx: 17.01,
            cy: 38.81,
            label: '1',
            orderIndex: 1,
          },
          {
            cx: 77.61,
            cy: 40.3,
            label: '2',
            orderIndex: 2,
          },
          {
            cx: 52.24,
            cy: 11.94,
            label: '3',
            orderIndex: 3,
          },
          {
            cx: 13.43,
            cy: 14.93,
            label: '4',
            orderIndex: 4,
          },
          {
            cx: 53.73,
            cy: 56.72,
            label: '5',
            orderIndex: 5,
          },
          {
            cx: 85.07,
            cy: 17.91,
            label: '6',
            orderIndex: 6,
          },
          {
            cx: 88.06,
            cy: 74.63,
            label: '7',
            orderIndex: 7,
          },
          {
            cx: 14.93,
            cy: 59.7,
            label: '8',
            orderIndex: 8,
          },
          {
            cx: 19.4,
            cy: 79.1,
            label: '9',
            orderIndex: 9,
          },
          {
            cx: 50.75,
            cy: 31.34,
            label: '10',
            orderIndex: 10,
          },
          {
            cx: 53.73,
            cy: 86.57,
            label: '11',
            orderIndex: 11,
          },
        ],
        tutorials: [
          {
            nodeLabel: null,
            text: 'On this screen are more numbers in circles.',
          },
          {
            nodeLabel: null,
            text: 'You will take a pen and draw a line from one circle to the next, in order.',
          },
          {
            nodeLabel: '1',
            text: 'Start at 1.',
          },
          {
            nodeLabel: '11',
            text: 'And End here.',
          },
          {
            nodeLabel: null,
            text: 'Please try not to lift the pen as you move from one circle to the next.',
          },
          {
            nodeLabel: null,
            text: 'Work as quickly as you can.',
          },
          {
            nodeLabel: null,
            text: 'Click next to start',
          },
        ],
      },
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e3204c-22d8-1858-d681-b9e100000000',
      inputType: 'AbTrails',
      isAbleToMoveBack: false,
      isHidden: false,
      isSkippable: false,
      name: 'trail2',
      order: 1,
      question: 'Test A',
      timer: null,
    },
    {
      canBeReset: false,
      config: {
        config: {
          beginWordLength: null,
          endWordLength: null,
          fontSize: 5.97,
          fontSizeBeginEnd: null,
          radius: 4.18,
        },
        deviceType: 'mobile',
        nodes: [
          {
            cx: 53.73,
            cy: 86.57,
            label: '1',
            orderIndex: 1,
          },
          {
            cx: 88.06,
            cy: 74.63,
            label: 'A',
            orderIndex: 2,
          },
          {
            cx: 85.07,
            cy: 17.91,
            label: '2',
            orderIndex: 3,
          },
          {
            cx: 52.24,
            cy: 11.94,
            label: 'B',
            orderIndex: 4,
          },
          {
            cx: 77.61,
            cy: 40.3,
            label: '3',
            orderIndex: 5,
          },
          {
            cx: 14.92,
            cy: 59.7,
            label: 'C',
            orderIndex: 6,
          },
          {
            cx: 50.75,
            cy: 31.34,
            label: '4',
            orderIndex: 7,
          },
          {
            cx: 13.43,
            cy: 14.92,
            label: 'D',
            orderIndex: 8,
          },
          {
            cx: 53.73,
            cy: 56.72,
            label: '5',
            orderIndex: 9,
          },
          {
            cx: 17.01,
            cy: 38.81,
            label: 'E',
            orderIndex: 10,
          },
          {
            cx: 19.4,
            cy: 79.1,
            label: '6',
            orderIndex: 11,
          },
        ],
        tutorials: [
          {
            nodeLabel: null,
            text: 'There are numbers and letters in circles on this screen.',
          },
          {
            nodeLabel: null,
            text: 'You will take a pen and draw a line alternating in order between the numbers and letters.',
          },
          {
            nodeLabel: '1',
            text: 'Start at number 1.',
          },
          {
            nodeLabel: 'A',
            text: 'Then go to the first letter A.',
          },
          {
            nodeLabel: '2',
            text: 'Then go to the next number 2.',
          },
          {
            nodeLabel: 'B',
            text: 'Then go to the next letter B, and so on.',
          },
          {
            nodeLabel: null,
            text: 'Please try not to lift the pen as you move from one number to the next. Work as quickly as you can.',
          },
          {
            nodeLabel: '1',
            text: 'Begin here.',
          },
          {
            nodeLabel: '6',
            text: 'And end here.',
          },
          {
            nodeLabel: null,
            text: 'Click next to start',
          },
        ],
      },
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e3204d-22d8-1858-d681-b9e200000000',
      inputType: 'AbTrails',
      isAbleToMoveBack: false,
      isHidden: false,
      isSkippable: false,
      name: 'trail3',
      order: 1,
      question: 'Sample B',
      timer: null,
    },
    {
      canBeReset: false,
      config: {
        config: {
          beginWordLength: null,
          endWordLength: null,
          fontSize: 5.97,
          fontSizeBeginEnd: null,
          radius: 4.18,
        },
        deviceType: 'mobile',
        nodes: [
          {
            cx: 50.75,
            cy: 31.34,
            label: '1',
            orderIndex: 1,
          },
          {
            cx: 13.43,
            cy: 14.93,
            label: 'A',
            orderIndex: 2,
          },
          {
            cx: 52.24,
            cy: 11.94,
            label: '2',
            orderIndex: 3,
          },
          {
            cx: 17.01,
            cy: 38.81,
            label: 'B',
            orderIndex: 4,
          },
          {
            cx: 77.61,
            cy: 40.3,
            label: '3',
            orderIndex: 5,
          },
          {
            cx: 85.07,
            cy: 17.91,
            label: 'C',
            orderIndex: 6,
          },
          {
            cx: 88.06,
            cy: 74.63,
            label: '4',
            orderIndex: 7,
          },
          {
            cx: 14.93,
            cy: 59.7,
            label: 'D',
            orderIndex: 8,
          },
          {
            cx: 53.73,
            cy: 56.72,
            label: '5',
            orderIndex: 9,
          },
          {
            cx: 19.4,
            cy: 79.1,
            label: 'E',
            orderIndex: 10,
          },
          {
            cx: 53.73,
            cy: 86.57,
            label: '6',
            orderIndex: 11,
          },
        ],
        tutorials: [
          {
            nodeLabel: null,
            text: 'On this screen there are more numbers and letters in circles.',
          },
          {
            nodeLabel: null,
            text: 'You will take a pen and draw a line from one circle to the next.',
          },
          {
            nodeLabel: null,
            text: 'Alternating in order between the numbers and letters.',
          },
          {
            nodeLabel: '1',
            text: 'Start at 1.',
          },
          {
            nodeLabel: '6',
            text: 'And end here.',
          },
          {
            nodeLabel: null,
            text: 'Please try not to lift the pen as you move from one circle to the next.',
          },
          {
            nodeLabel: null,
            text: 'Work as quickly as you can.',
          },
          {
            nodeLabel: null,
            text: 'Click next to start',
          },
        ],
      },
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e3204e-22d8-1858-d681-b9e300000000',
      inputType: 'AbTrails',
      isAbleToMoveBack: false,
      isHidden: false,
      isSkippable: false,
      name: 'trail4',
      order: 1,
      question: 'Test B',
      timer: null,
    },
  ],
  name: 'Trails_Mobile',
  order: 2,
  responseIsEditable: true,
  scoreSettings: [],
  showAllAtOnce: false,
  splashScreen: '',
};
