import { ActivityDetails } from '@entities/activity';
import {
  ABTrailsItemDto,
  FlankerItemDto,
  StabilityTrackerItemDto,
} from '@shared/api';

export const abTrailsInput = {
  id: '64e32047-22d8-1858-d681-b9d600000000',
  name: 'Trails_Mobile',
  description: 'A/B Trails',
  splashScreen: '',
  image: '',
  showAllAtOnce: false,
  isSkippable: false,
  isReviewable: false,
  isHidden: false,
  responseIsEditable: true,
  order: 2,
  items: [
    {
      question: 'Sample A',
      responseType: 'ABTrails',
      responseValues: null,
      config: {
        deviceType: 'mobile',
        orderName: 'first',
        tutorials: {
          tutorials: [
            {
              text: 'There are numbers in circles on this screen.',
              nodeLabel: null,
            },
            {
              text: 'You will take a pen and draw a line from one number to the next, in order.',
              nodeLabel: null,
            },
            { text: 'Start at 1.', nodeLabel: '1' },
            { text: 'Then go to 2.', nodeLabel: '2' },
            { text: 'Then 3, and so on.', nodeLabel: '3' },
            {
              text: 'Please try not to lift the pen as you move from one number to the next. Work as quickly as you can.',
              nodeLabel: null,
            },
            { text: 'Begin here.', nodeLabel: '1' },
            { text: 'And end here.', nodeLabel: '11' },
            { text: 'Click next to start', nodeLabel: null },
          ],
        },
        nodes: {
          radius: 4.18,
          fontSize: 5.6,
          fontSizeBeginEnd: null,
          beginWordLength: null,
          endWordLength: null,
          nodes: [
            { orderIndex: 1, cx: 52.24, cy: 11.94, label: '1' },
            { orderIndex: 2, cx: 85.07, cy: 17.91, label: '2' },
            { orderIndex: 3, cx: 88.06, cy: 74.63, label: '3' },
            { orderIndex: 4, cx: 53.73, cy: 86.57, label: '4' },
            { orderIndex: 5, cx: 77.61, cy: 40.3, label: '5' },
            { orderIndex: 6, cx: 17.01, cy: 38.81, label: '6' },
            { orderIndex: 7, cx: 53.73, cy: 56.72, label: '7' },
            { orderIndex: 8, cx: 19.4, cy: 79.1, label: '8' },
            { orderIndex: 9, cx: 14.93, cy: 59.7, label: '9' },
            { orderIndex: 10, cx: 50.75, cy: 31.34, label: '10' },
            { orderIndex: 11, cx: 13.43, cy: 14.93, label: '11' },
          ],
        },
      },
      name: 'trail1',
      isHidden: false,
      conditionalLogic: null,
      allowEdit: true,
      id: '64e3204b-22d8-1858-d681-b9e000000000',
      order: 1,
      timer: null,
    } as ABTrailsItemDto,
    {
      question: 'Test A',
      responseType: 'ABTrails',
      responseValues: null,
      config: {
        deviceType: 'mobile',
        orderName: 'second',
        tutorials: {
          tutorials: [
            {
              text: 'On this screen are more numbers in circles.',
              nodeLabel: null,
            },
            {
              text: 'You will take a pen and draw a line from one circle to the next, in order.',
              nodeLabel: null,
            },
            { text: 'Start at 1.', nodeLabel: '1' },
            { text: 'And End here.', nodeLabel: '11' },
            {
              text: 'Please try not to lift the pen as you move from one circle to the next.',
              nodeLabel: null,
            },
            { text: 'Work as quickly as you can.', nodeLabel: null },
            { text: 'Click next to start', nodeLabel: null },
          ],
        },
        nodes: {
          radius: 4.18,
          fontSize: 5.97,
          fontSizeBeginEnd: null,
          beginWordLength: null,
          endWordLength: null,
          nodes: [
            { orderIndex: 1, cx: 17.01, cy: 38.81, label: '1' },
            { orderIndex: 2, cx: 77.61, cy: 40.3, label: '2' },
            { orderIndex: 3, cx: 52.24, cy: 11.94, label: '3' },
            { orderIndex: 4, cx: 13.43, cy: 14.93, label: '4' },
            { orderIndex: 5, cx: 53.73, cy: 56.72, label: '5' },
            { orderIndex: 6, cx: 85.07, cy: 17.91, label: '6' },
            { orderIndex: 7, cx: 88.06, cy: 74.63, label: '7' },
            { orderIndex: 8, cx: 14.93, cy: 59.7, label: '8' },
            { orderIndex: 9, cx: 19.4, cy: 79.1, label: '9' },
            { orderIndex: 10, cx: 50.75, cy: 31.34, label: '10' },
            { orderIndex: 11, cx: 53.73, cy: 86.57, label: '11' },
          ],
        },
      },
      name: 'trail2',
      isHidden: false,
      conditionalLogic: null,
      allowEdit: true,
      id: '64e3204c-22d8-1858-d681-b9e100000000',

      order: 1,
      timer: null,
    } as ABTrailsItemDto,
    {
      question: 'Sample B',
      responseType: 'ABTrails',
      responseValues: null,
      config: {
        deviceType: 'mobile',
        orderName: 'third',
        tutorials: {
          tutorials: [
            {
              text: 'There are numbers and letters in circles on this screen.',
              nodeLabel: null,
            },
            {
              text: 'You will take a pen and draw a line alternating in order between the numbers and letters.',
              nodeLabel: null,
            },
            { text: 'Start at number 1.', nodeLabel: '1' },
            { text: 'Then go to the first letter A.', nodeLabel: 'A' },
            { text: 'Then go to the next number 2.', nodeLabel: '2' },
            {
              text: 'Then go to the next letter B, and so on.',
              nodeLabel: 'B',
            },
            {
              text: 'Please try not to lift the pen as you move from one number to the next. Work as quickly as you can.',
              nodeLabel: null,
            },
            { text: 'Begin here.', nodeLabel: '1' },
            { text: 'And end here.', nodeLabel: '6' },
            { text: 'Click next to start', nodeLabel: null },
          ],
        },
        nodes: {
          radius: 4.18,
          fontSize: 5.97,
          fontSizeBeginEnd: null,
          beginWordLength: null,
          endWordLength: null,
          nodes: [
            { orderIndex: 1, cx: 53.73, cy: 86.57, label: '1' },
            { orderIndex: 2, cx: 88.06, cy: 74.63, label: 'A' },
            { orderIndex: 3, cx: 85.07, cy: 17.91, label: '2' },
            { orderIndex: 4, cx: 52.24, cy: 11.94, label: 'B' },
            { orderIndex: 5, cx: 77.61, cy: 40.3, label: '3' },
            { orderIndex: 6, cx: 14.92, cy: 59.7, label: 'C' },
            { orderIndex: 7, cx: 50.75, cy: 31.34, label: '4' },
            { orderIndex: 8, cx: 13.43, cy: 14.92, label: 'D' },
            { orderIndex: 9, cx: 53.73, cy: 56.72, label: '5' },
            { orderIndex: 10, cx: 17.01, cy: 38.81, label: 'E' },
            { orderIndex: 11, cx: 19.4, cy: 79.1, label: '6' },
          ],
        },
      },
      name: 'trail3',
      isHidden: false,
      conditionalLogic: null,
      allowEdit: true,
      id: '64e3204d-22d8-1858-d681-b9e200000000',

      order: 1,
      timer: null,
    } as ABTrailsItemDto,
    {
      question: 'Test B',
      responseType: 'ABTrails',
      responseValues: null,
      config: {
        deviceType: 'mobile',
        orderName: 'fourth',
        tutorials: {
          tutorials: [
            {
              text: 'On this screen there are more numbers and letters in circles.',
              nodeLabel: null,
            },
            {
              text: 'You will take a pen and draw a line from one circle to the next.',
              nodeLabel: null,
            },
            {
              text: 'Alternating in order between the numbers and letters.',
              nodeLabel: null,
            },
            { text: 'Start at 1.', nodeLabel: '1' },
            { text: 'And end here.', nodeLabel: '6' },
            {
              text: 'Please try not to lift the pen as you move from one circle to the next.',
              nodeLabel: null,
            },
            { text: 'Work as quickly as you can.', nodeLabel: null },
            { text: 'Click next to start', nodeLabel: null },
          ],
        },
        nodes: {
          radius: 4.18,
          fontSize: 5.97,
          fontSizeBeginEnd: null,
          beginWordLength: null,
          endWordLength: null,
          nodes: [
            { orderIndex: 1, cx: 50.75, cy: 31.34, label: '1' },
            { orderIndex: 2, cx: 13.43, cy: 14.93, label: 'A' },
            { orderIndex: 3, cx: 52.24, cy: 11.94, label: '2' },
            { orderIndex: 4, cx: 17.01, cy: 38.81, label: 'B' },
            { orderIndex: 5, cx: 77.61, cy: 40.3, label: '3' },
            { orderIndex: 6, cx: 85.07, cy: 17.91, label: 'C' },
            { orderIndex: 7, cx: 88.06, cy: 74.63, label: '4' },
            { orderIndex: 8, cx: 14.93, cy: 59.7, label: 'D' },
            { orderIndex: 9, cx: 53.73, cy: 56.72, label: '5' },
            { orderIndex: 10, cx: 19.4, cy: 79.1, label: 'E' },
            { orderIndex: 11, cx: 53.73, cy: 86.57, label: '6' },
          ],
        },
      },
      name: 'trail4',
      isHidden: false,
      conditionalLogic: null,
      allowEdit: true,
      id: '64e3204e-22d8-1858-d681-b9e300000000',

      order: 1,
      timer: null,
    } as ABTrailsItemDto,
  ],
  scoresAndReports: {
    generateReport: false,
    showScoreSummary: false,
    reports: [],
  },
};
export const abTrailsOutput = {
  description: 'A/B Trails',
  hasSummary: false,
  id: '64e32047-22d8-1858-d681-b9d600000000',
  image: '',
  isHidden: false,
  isReviewable: false,
  isSkippable: false,
  items: [
    {
      canBeReset: false,
      config: {
        config: {
          beginWordLength: null,
          endWordLength: null,
          fontSize: 5.6,
          fontSizeBeginEnd: null,
          radius: 4.18,
        },
        deviceType: 'mobile',
        nodes: [
          {
            cx: 52.24,
            cy: 11.94,
            label: '1',
            orderIndex: 1,
          },
          {
            cx: 85.07,
            cy: 17.91,
            label: '2',
            orderIndex: 2,
          },
          {
            cx: 88.06,
            cy: 74.63,
            label: '3',
            orderIndex: 3,
          },
          {
            cx: 53.73,
            cy: 86.57,
            label: '4',
            orderIndex: 4,
          },
          {
            cx: 77.61,
            cy: 40.3,
            label: '5',
            orderIndex: 5,
          },
          {
            cx: 17.01,
            cy: 38.81,
            label: '6',
            orderIndex: 6,
          },
          {
            cx: 53.73,
            cy: 56.72,
            label: '7',
            orderIndex: 7,
          },
          {
            cx: 19.4,
            cy: 79.1,
            label: '8',
            orderIndex: 8,
          },
          {
            cx: 14.93,
            cy: 59.7,
            label: '9',
            orderIndex: 9,
          },
          {
            cx: 50.75,
            cy: 31.34,
            label: '10',
            orderIndex: 10,
          },
          {
            cx: 13.43,
            cy: 14.93,
            label: '11',
            orderIndex: 11,
          },
        ],
        tutorials: [
          {
            nodeLabel: null,
            text: 'There are numbers in circles on this screen.',
          },
          {
            nodeLabel: null,
            text: 'You will take a pen and draw a line from one number to the next, in order.',
          },
          {
            nodeLabel: '1',
            text: 'Start at 1.',
          },
          {
            nodeLabel: '2',
            text: 'Then go to 2.',
          },
          {
            nodeLabel: '3',
            text: 'Then 3, and so on.',
          },
          {
            nodeLabel: null,
            text: 'Please try not to lift the pen as you move from one number to the next. Work as quickly as you can.',
          },
          {
            nodeLabel: '1',
            text: 'Begin here.',
          },
          {
            nodeLabel: '11',
            text: 'And end here.',
          },
          {
            nodeLabel: null,
            text: 'Click next to start',
          },
        ],
      },
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e3204b-22d8-1858-d681-b9e000000000',
      inputType: 'AbTrails',
      isAbleToMoveBack: false,
      isHidden: false,
      isSkippable: false,
      name: 'trail1',
      order: 1,
      question: 'Sample A',
      timer: null,
    },
    {
      canBeReset: false,
      config: {
        config: {
          beginWordLength: null,
          endWordLength: null,
          fontSize: 5.97,
          fontSizeBeginEnd: null,
          radius: 4.18,
        },
        deviceType: 'mobile',
        nodes: [
          {
            cx: 17.01,
            cy: 38.81,
            label: '1',
            orderIndex: 1,
          },
          {
            cx: 77.61,
            cy: 40.3,
            label: '2',
            orderIndex: 2,
          },
          {
            cx: 52.24,
            cy: 11.94,
            label: '3',
            orderIndex: 3,
          },
          {
            cx: 13.43,
            cy: 14.93,
            label: '4',
            orderIndex: 4,
          },
          {
            cx: 53.73,
            cy: 56.72,
            label: '5',
            orderIndex: 5,
          },
          {
            cx: 85.07,
            cy: 17.91,
            label: '6',
            orderIndex: 6,
          },
          {
            cx: 88.06,
            cy: 74.63,
            label: '7',
            orderIndex: 7,
          },
          {
            cx: 14.93,
            cy: 59.7,
            label: '8',
            orderIndex: 8,
          },
          {
            cx: 19.4,
            cy: 79.1,
            label: '9',
            orderIndex: 9,
          },
          {
            cx: 50.75,
            cy: 31.34,
            label: '10',
            orderIndex: 10,
          },
          {
            cx: 53.73,
            cy: 86.57,
            label: '11',
            orderIndex: 11,
          },
        ],
        tutorials: [
          {
            nodeLabel: null,
            text: 'On this screen are more numbers in circles.',
          },
          {
            nodeLabel: null,
            text: 'You will take a pen and draw a line from one circle to the next, in order.',
          },
          {
            nodeLabel: '1',
            text: 'Start at 1.',
          },
          {
            nodeLabel: '11',
            text: 'And End here.',
          },
          {
            nodeLabel: null,
            text: 'Please try not to lift the pen as you move from one circle to the next.',
          },
          {
            nodeLabel: null,
            text: 'Work as quickly as you can.',
          },
          {
            nodeLabel: null,
            text: 'Click next to start',
          },
        ],
      },
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e3204c-22d8-1858-d681-b9e100000000',
      inputType: 'AbTrails',
      isAbleToMoveBack: false,
      isHidden: false,
      isSkippable: false,
      name: 'trail2',
      order: 1,
      question: 'Test A',
      timer: null,
    },
    {
      canBeReset: false,
      config: {
        config: {
          beginWordLength: null,
          endWordLength: null,
          fontSize: 5.97,
          fontSizeBeginEnd: null,
          radius: 4.18,
        },
        deviceType: 'mobile',
        nodes: [
          {
            cx: 53.73,
            cy: 86.57,
            label: '1',
            orderIndex: 1,
          },
          {
            cx: 88.06,
            cy: 74.63,
            label: 'A',
            orderIndex: 2,
          },
          {
            cx: 85.07,
            cy: 17.91,
            label: '2',
            orderIndex: 3,
          },
          {
            cx: 52.24,
            cy: 11.94,
            label: 'B',
            orderIndex: 4,
          },
          {
            cx: 77.61,
            cy: 40.3,
            label: '3',
            orderIndex: 5,
          },
          {
            cx: 14.92,
            cy: 59.7,
            label: 'C',
            orderIndex: 6,
          },
          {
            cx: 50.75,
            cy: 31.34,
            label: '4',
            orderIndex: 7,
          },
          {
            cx: 13.43,
            cy: 14.92,
            label: 'D',
            orderIndex: 8,
          },
          {
            cx: 53.73,
            cy: 56.72,
            label: '5',
            orderIndex: 9,
          },
          {
            cx: 17.01,
            cy: 38.81,
            label: 'E',
            orderIndex: 10,
          },
          {
            cx: 19.4,
            cy: 79.1,
            label: '6',
            orderIndex: 11,
          },
        ],
        tutorials: [
          {
            nodeLabel: null,
            text: 'There are numbers and letters in circles on this screen.',
          },
          {
            nodeLabel: null,
            text: 'You will take a pen and draw a line alternating in order between the numbers and letters.',
          },
          {
            nodeLabel: '1',
            text: 'Start at number 1.',
          },
          {
            nodeLabel: 'A',
            text: 'Then go to the first letter A.',
          },
          {
            nodeLabel: '2',
            text: 'Then go to the next number 2.',
          },
          {
            nodeLabel: 'B',
            text: 'Then go to the next letter B, and so on.',
          },
          {
            nodeLabel: null,
            text: 'Please try not to lift the pen as you move from one number to the next. Work as quickly as you can.',
          },
          {
            nodeLabel: '1',
            text: 'Begin here.',
          },
          {
            nodeLabel: '6',
            text: 'And end here.',
          },
          {
            nodeLabel: null,
            text: 'Click next to start',
          },
        ],
      },
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e3204d-22d8-1858-d681-b9e200000000',
      inputType: 'AbTrails',
      isAbleToMoveBack: false,
      isHidden: false,
      isSkippable: false,
      name: 'trail3',
      order: 1,
      question: 'Sample B',
      timer: null,
    },
    {
      canBeReset: false,
      config: {
        config: {
          beginWordLength: null,
          endWordLength: null,
          fontSize: 5.97,
          fontSizeBeginEnd: null,
          radius: 4.18,
        },
        deviceType: 'mobile',
        nodes: [
          {
            cx: 50.75,
            cy: 31.34,
            label: '1',
            orderIndex: 1,
          },
          {
            cx: 13.43,
            cy: 14.93,
            label: 'A',
            orderIndex: 2,
          },
          {
            cx: 52.24,
            cy: 11.94,
            label: '2',
            orderIndex: 3,
          },
          {
            cx: 17.01,
            cy: 38.81,
            label: 'B',
            orderIndex: 4,
          },
          {
            cx: 77.61,
            cy: 40.3,
            label: '3',
            orderIndex: 5,
          },
          {
            cx: 85.07,
            cy: 17.91,
            label: 'C',
            orderIndex: 6,
          },
          {
            cx: 88.06,
            cy: 74.63,
            label: '4',
            orderIndex: 7,
          },
          {
            cx: 14.93,
            cy: 59.7,
            label: 'D',
            orderIndex: 8,
          },
          {
            cx: 53.73,
            cy: 56.72,
            label: '5',
            orderIndex: 9,
          },
          {
            cx: 19.4,
            cy: 79.1,
            label: 'E',
            orderIndex: 10,
          },
          {
            cx: 53.73,
            cy: 86.57,
            label: '6',
            orderIndex: 11,
          },
        ],
        tutorials: [
          {
            nodeLabel: null,
            text: 'On this screen there are more numbers and letters in circles.',
          },
          {
            nodeLabel: null,
            text: 'You will take a pen and draw a line from one circle to the next.',
          },
          {
            nodeLabel: null,
            text: 'Alternating in order between the numbers and letters.',
          },
          {
            nodeLabel: '1',
            text: 'Start at 1.',
          },
          {
            nodeLabel: '6',
            text: 'And end here.',
          },
          {
            nodeLabel: null,
            text: 'Please try not to lift the pen as you move from one circle to the next.',
          },
          {
            nodeLabel: null,
            text: 'Work as quickly as you can.',
          },
          {
            nodeLabel: null,
            text: 'Click next to start',
          },
        ],
      },
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e3204e-22d8-1858-d681-b9e300000000',
      inputType: 'AbTrails',
      isAbleToMoveBack: false,
      isHidden: false,
      isSkippable: false,
      name: 'trail4',
      order: 1,
      question: 'Test B',
      timer: null,
    },
  ],
  name: 'Trails_Mobile',
  order: 2,
  responseIsEditable: true,
  scoreSettings: [],
  scoresAndReports: {
    generateReport: false,
    reports: [],
    showScoreSummary: false,
  },
  showAllAtOnce: false,
  splashScreen: '',
} as ActivityDetails;

export const flankerInput = {
  id: '64e32047-22d8-1858-d681-b9d700000000',
  name: 'Simple & Choice Reaction Time Task Builder',
  description: '75%; no fixation; randomize',
  splashScreen: '',
  image: '',
  showAllAtOnce: false,
  isSkippable: false,
  isReviewable: false,
  isHidden: false,
  responseIsEditable: true,
  order: 3,
  items: [
    {
      question:
        '## General Instructions\n\n\n You will see arrows presented at the center of the screen that point either to the left ‘<’ or right ‘>’.\n Press the left button if the arrow is pointing to the left ‘<’ or press the right button if the arrow is pointing to the right ‘>’.\n These arrows will appear in the center of a line of other items. Sometimes, these other items will be arrows pointing in the same direction, e.g.. ‘> > > > >’, or in the opposite direction, e.g. ‘< < > < <’.\n Your job is to respond to the central arrow, no matter what direction the other arrows are pointing.\n For example, you would press the left button for both ‘< < < < <’, and ‘> > < > >’ because the middle arrow points to the left.\n Finally, in some trials dashes ‘ - ’ will appear beside the central arrow.\n Again, respond only to the direction of the central arrow. Please respond as quickly and accurately as possible.',
      responseType: 'message',
      responseValues: null,
      config: { removeBackButton: false, timer: null },
      name: 'vsr-instructions',
      isHidden: false,
      conditionalLogic: null,
      allowEdit: true,
      id: '64e3204e-22d8-1858-d681-b9e400000000',
    },
    {
      question:
        '## Instructions\n\nNow you will have a chance to practice the task before moving on to the test phase.\nRemember to respond only to the central arrow\n',
      responseType: 'message',
      responseValues: null,
      config: { removeBackButton: false, timer: null },
      name: 'practice-instructions',
      isHidden: false,
      conditionalLogic: null,
      allowEdit: true,
      id: '64e3204e-22d8-1858-d681-b9e500000000',
    },
    {
      question: '',
      responseType: 'flanker',
      responseValues: null,
      config: {
        stimulusTrials: [
          {
            id: '5__png0',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/uT9zciGBfB5d7EXu7oyN8g.png',
            text: '5.png',
            value: 0,
            weight: null,
          },
          {
            id: 'image__1__png1',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/2F159Gsy66NdSgrdgsFAXL.png',
            text: 'image 1.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__2__png2',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/swBFCcF4DaGyXEusHY6PQK.png',
            text: 'IMAGE 2.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__png3',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/qgYVs1v9yVcE48B2psKuBP.png',
            text: 'IMAGE.png',
            value: 0,
            weight: null,
          },
          {
            id: 'iMAGE__3__png4',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/o68MKdhg2rJZ4sQG8UoEqL.png',
            text: 'iMAGE_3.png',
            value: 1,
            weight: null,
          },
          {
            id: '____________6__png5',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/tk8KsE56LsMW5vepDQrc5K.png',
            text: 'ШЬФПУ 6.png',
            value: 1,
            weight: null,
          },
        ],
        blocks: [
          {
            name: 'block 1',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 2',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 3',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 4',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
        ],
        buttons: [
          { text: 'HOME', image: null, value: 0 },
          { text: 'WILD', image: null, value: 1 },
        ],
        nextButton: 'OK',
        fixationDuration: 0,
        fixationScreen: null,
        minimumAccuracy: 75,
        sampleSize: 1,
        samplingMethod: 'randomize-order',
        showFeedback: true,
        showFixation: false,
        showResults: true,
        trialDuration: 3000,
        isLastPractice: false,
        isFirstPractice: false,
        isLastTest: false,
        blockType: 'practice',
      },
      name: 'trial',
      isHidden: false,
      conditionalLogic: null,
      allowEdit: true,
      id: '64e3204f-22d8-1858-d681-b9e600000000',
    },
    {
      question: '## Instructions\nPress the Next button to restart block.',
      responseType: 'message',
      responseValues: null,
      config: { removeBackButton: false, timer: null },
      name: 'trial2-instructions',
      isHidden: false,
      conditionalLogic: null,
      allowEdit: true,
      id: '64e3204f-22d8-1858-d681-b9e700000000',
    },
    {
      question: '',
      responseType: 'flanker',
      responseValues: null,
      config: {
        stimulusTrials: [
          {
            id: '5__png0',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/uT9zciGBfB5d7EXu7oyN8g.png',
            text: '5.png',
            value: 0,
            weight: null,
          },
          {
            id: 'image__1__png1',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/2F159Gsy66NdSgrdgsFAXL.png',
            text: 'image 1.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__2__png2',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/swBFCcF4DaGyXEusHY6PQK.png',
            text: 'IMAGE 2.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__png3',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/qgYVs1v9yVcE48B2psKuBP.png',
            text: 'IMAGE.png',
            value: 0,
            weight: null,
          },
          {
            id: 'iMAGE__3__png4',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/o68MKdhg2rJZ4sQG8UoEqL.png',
            text: 'iMAGE_3.png',
            value: 1,
            weight: null,
          },
          {
            id: '____________6__png5',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/tk8KsE56LsMW5vepDQrc5K.png',
            text: 'ШЬФПУ 6.png',
            value: 1,
            weight: null,
          },
        ],
        blocks: [
          {
            name: 'block 1',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 2',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 3',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 4',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
        ],
        buttons: [
          { text: 'HOME', image: null, value: 0 },
          { text: 'WILD', image: null, value: 1 },
        ],
        nextButton: 'OK',
        fixationDuration: 0,
        fixationScreen: null,
        minimumAccuracy: 75,
        sampleSize: 1,
        samplingMethod: 'randomize-order',
        showFeedback: true,
        showFixation: false,
        showResults: true,
        trialDuration: 3000,
        isLastPractice: false,
        isFirstPractice: false,
        isLastTest: false,
        blockType: 'practice',
      },
      name: 'trial2',
      isHidden: false,
      conditionalLogic: null,
      allowEdit: true,
      id: '64e3204f-22d8-1858-d681-b9e800000000',
    },
    {
      question: '## Instructions\nPress the Next button to restart block.',
      responseType: 'message',
      responseValues: null,
      config: { removeBackButton: false, timer: null },
      name: 'trial3-instructions',
      isHidden: false,
      conditionalLogic: null,
      allowEdit: true,
      id: '64e3204f-22d8-1858-d681-b9e900000000',
    },
    {
      question: '',
      responseType: 'flanker',
      responseValues: null,
      config: {
        stimulusTrials: [
          {
            id: '5__png0',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/uT9zciGBfB5d7EXu7oyN8g.png',
            text: '5.png',
            value: 0,
            weight: null,
          },
          {
            id: 'image__1__png1',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/2F159Gsy66NdSgrdgsFAXL.png',
            text: 'image 1.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__2__png2',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/swBFCcF4DaGyXEusHY6PQK.png',
            text: 'IMAGE 2.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__png3',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/qgYVs1v9yVcE48B2psKuBP.png',
            text: 'IMAGE.png',
            value: 0,
            weight: null,
          },
          {
            id: 'iMAGE__3__png4',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/o68MKdhg2rJZ4sQG8UoEqL.png',
            text: 'iMAGE_3.png',
            value: 1,
            weight: null,
          },
          {
            id: '____________6__png5',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/tk8KsE56LsMW5vepDQrc5K.png',
            text: 'ШЬФПУ 6.png',
            value: 1,
            weight: null,
          },
        ],
        blocks: [
          {
            name: 'block 1',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 2',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 3',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 4',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
        ],
        buttons: [
          { text: 'HOME', image: null, value: 0 },
          { text: 'WILD', image: null, value: 1 },
        ],
        nextButton: 'OK',
        fixationDuration: 0,
        fixationScreen: null,
        minimumAccuracy: 75,
        sampleSize: 1,
        samplingMethod: 'randomize-order',
        showFeedback: true,
        showFixation: false,
        showResults: true,
        trialDuration: 3000,
        isLastPractice: true,
        isFirstPractice: false,
        isLastTest: false,
        blockType: 'practice',
      },
      name: 'trial3',
      isHidden: false,
      conditionalLogic: null,
      allowEdit: true,
      id: '64e32050-22d8-1858-d681-b9ea00000000',
    },
    {
      question:
        '## Test Instructions\n\nGood job on the practice blocks.\nYou can now move on to the test blocks.\nYou will do the same task as in the practice, responding to the direction of the central arrow.\nYou will complete 3 blocks, each about 3-5 minutes long.\nYou will have  a short break in between these blocks\n',
      responseType: 'message',
      responseValues: null,
      config: { removeBackButton: false, timer: null },
      name: 'test-instructions',
      isHidden: false,
      conditionalLogic: null,
      allowEdit: true,
      id: '64e32050-22d8-1858-d681-b9eb00000000',
    },
    {
      question: '',
      responseType: 'flanker',
      responseValues: null,
      config: {
        stimulusTrials: [
          {
            id: '5__png0',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/uT9zciGBfB5d7EXu7oyN8g.png',
            text: '5.png',
            value: 0,
            weight: null,
          },
          {
            id: 'image__1__png1',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/2F159Gsy66NdSgrdgsFAXL.png',
            text: 'image 1.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__2__png2',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/swBFCcF4DaGyXEusHY6PQK.png',
            text: 'IMAGE 2.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__png3',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/qgYVs1v9yVcE48B2psKuBP.png',
            text: 'IMAGE.png',
            value: 0,
            weight: null,
          },
          {
            id: 'iMAGE__3__png4',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/o68MKdhg2rJZ4sQG8UoEqL.png',
            text: 'iMAGE_3.png',
            value: 1,
            weight: null,
          },
          {
            id: '____________6__png5',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/tk8KsE56LsMW5vepDQrc5K.png',
            text: 'ШЬФПУ 6.png',
            value: 1,
            weight: null,
          },
        ],
        blocks: [
          {
            name: 'block 1',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 2',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 3',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 4',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
        ],
        buttons: [
          { text: 'HOME', image: null, value: 0 },
          { text: 'WILD', image: null, value: 1 },
        ],
        nextButton: 'Continue',
        fixationDuration: 0,
        fixationScreen: null,
        minimumAccuracy: null,
        sampleSize: 1,
        samplingMethod: 'randomize-order',
        showFeedback: false,
        showFixation: false,
        showResults: true,
        trialDuration: 3000,
        isLastPractice: false,
        isFirstPractice: false,
        isLastTest: false,
        blockType: 'test',
      },
      name: 'test1',
      isHidden: false,
      conditionalLogic: null,
      allowEdit: true,
      id: '64e32050-22d8-1858-d681-b9ec00000000',
    },
    {
      question: '## Instructions\nPress the Next button to start next block.',
      responseType: 'message',
      responseValues: null,
      config: { removeBackButton: false, timer: null },
      name: 'test2-instructions',
      isHidden: false,
      conditionalLogic: null,
      allowEdit: true,
      id: '64e32051-22d8-1858-d681-b9ed00000000',
    },
    {
      question: '',
      responseType: 'flanker',
      responseValues: null,
      config: {
        stimulusTrials: [
          {
            id: '5__png0',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/uT9zciGBfB5d7EXu7oyN8g.png',
            text: '5.png',
            value: 0,
            weight: null,
          },
          {
            id: 'image__1__png1',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/2F159Gsy66NdSgrdgsFAXL.png',
            text: 'image 1.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__2__png2',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/swBFCcF4DaGyXEusHY6PQK.png',
            text: 'IMAGE 2.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__png3',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/qgYVs1v9yVcE48B2psKuBP.png',
            text: 'IMAGE.png',
            value: 0,
            weight: null,
          },
          {
            id: 'iMAGE__3__png4',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/o68MKdhg2rJZ4sQG8UoEqL.png',
            text: 'iMAGE_3.png',
            value: 1,
            weight: null,
          },
          {
            id: '____________6__png5',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/tk8KsE56LsMW5vepDQrc5K.png',
            text: 'ШЬФПУ 6.png',
            value: 1,
            weight: null,
          },
        ],
        blocks: [
          {
            name: 'block 1',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 2',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 3',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 4',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
        ],
        buttons: [
          { text: 'HOME', image: null, value: 0 },
          { text: 'WILD', image: null, value: 1 },
        ],
        nextButton: 'Continue',
        fixationDuration: 0,
        fixationScreen: null,
        minimumAccuracy: null,
        sampleSize: 1,
        samplingMethod: 'randomize-order',
        showFeedback: false,
        showFixation: false,
        showResults: true,
        trialDuration: 3000,
        isLastPractice: false,
        isFirstPractice: false,
        isLastTest: false,
        blockType: 'test',
      },
      name: 'test2',
      isHidden: false,
      conditionalLogic: null,
      allowEdit: true,
      id: '64e32051-22d8-1858-d681-b9ee00000000',
    },
    {
      question: '## Instructions\nPress the Next button to start next block.',
      responseType: 'message',
      responseValues: null,
      config: { removeBackButton: false, timer: null },
      name: 'test3-instructions',
      isHidden: false,
      conditionalLogic: null,
      allowEdit: true,
      id: '64e32051-22d8-1858-d681-b9ef00000000',
    },
    {
      question: '',
      responseType: 'flanker',
      responseValues: null,
      config: {
        stimulusTrials: [
          {
            id: '5__png0',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/uT9zciGBfB5d7EXu7oyN8g.png',
            text: '5.png',
            value: 0,
            weight: null,
          },
          {
            id: 'image__1__png1',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/2F159Gsy66NdSgrdgsFAXL.png',
            text: 'image 1.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__2__png2',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/swBFCcF4DaGyXEusHY6PQK.png',
            text: 'IMAGE 2.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__png3',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/qgYVs1v9yVcE48B2psKuBP.png',
            text: 'IMAGE.png',
            value: 0,
            weight: null,
          },
          {
            id: 'iMAGE__3__png4',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/o68MKdhg2rJZ4sQG8UoEqL.png',
            text: 'iMAGE_3.png',
            value: 1,
            weight: null,
          },
          {
            id: '____________6__png5',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/tk8KsE56LsMW5vepDQrc5K.png',
            text: 'ШЬФПУ 6.png',
            value: 1,
            weight: null,
          },
        ],
        blocks: [
          {
            name: 'block 1',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 2',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 3',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 4',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
        ],
        buttons: [
          { text: 'HOME', image: null, value: 0 },
          { text: 'WILD', image: null, value: 1 },
        ],
        nextButton: 'Continue',
        fixationDuration: 0,
        fixationScreen: { value: '', image: '' },
        minimumAccuracy: 2,
        sampleSize: 1,
        samplingMethod: 'randomize-order',
        showFeedback: false,
        showFixation: false,
        showResults: true,
        trialDuration: 3000,
        isLastPractice: false,
        isFirstPractice: false,
        isLastTest: true,
        blockType: 'test',
      },
      name: 'test3',
      isHidden: false,
      conditionalLogic: null,
      id: '64e32052-22d8-1858-d681-b9f000000000',
      order: 1,
      timer: null,
    },
  ] as FlankerItemDto[],
  scoresAndReports: {
    generateReport: false,
    showScoreSummary: false,
    reports: [],
  },
};
export const flankerOutput = {
  description: '75%; no fixation; randomize',
  hasSummary: false,
  id: '64e32047-22d8-1858-d681-b9d700000000',
  image: '',
  isHidden: false,
  isReviewable: false,
  isSkippable: false,
  items: [
    {
      canBeReset: false,
      config: null,
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e3204e-22d8-1858-d681-b9e400000000',
      inputType: 'Message',
      isAbleToMoveBack: true,
      isHidden: false,
      isSkippable: false,
      name: 'vsr-instructions',
      question:
        '## General Instructions\n\n\n You will see arrows presented at the center of the screen that point either to the left ‘<’ or right ‘>’.\n Press the left button if the arrow is pointing to the left ‘<’ or press the right button if the arrow is pointing to the right ‘>’.\n These arrows will appear in the center of a line of other items. Sometimes, these other items will be arrows pointing in the same direction, e.g.. ‘> > > > >’, or in the opposite direction, e.g. ‘< < > < <’.\n Your job is to respond to the central arrow, no matter what direction the other arrows are pointing.\n For example, you would press the left button for both ‘< < < < <’, and ‘> > < > >’ because the middle arrow points to the left.\n Finally, in some trials dashes ‘ - ’ will appear beside the central arrow.\n Again, respond only to the direction of the central arrow. Please respond as quickly and accurately as possible.',
      timer: null,
    },
    {
      canBeReset: false,
      config: null,
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e3204e-22d8-1858-d681-b9e500000000',
      inputType: 'Message',
      isAbleToMoveBack: true,
      isHidden: false,
      isSkippable: false,
      name: 'practice-instructions',
      question:
        '## Instructions\n\nNow you will have a chance to practice the task before moving on to the test phase.\nRemember to respond only to the central arrow\n',
      timer: null,
    },
    {
      canBeReset: false,
      config: {
        blockType: 'practice',
        blocks: [
          {
            name: 'block 1',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 2',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 3',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 4',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
        ],
        buttons: [
          {
            image: null,
            text: 'HOME',
            value: 0,
          },
          {
            image: null,
            text: 'WILD',
            value: 1,
          },
        ],
        fixationDuration: 0,
        fixationScreen: {
          image: '',
          value: '',
        },
        isFirstPractice: false,
        isLastPractice: false,
        isLastTest: false,
        minimumAccuracy: 75,
        nextButton: 'OK',
        sampleSize: 1,
        samplingMethod: 'randomize-order',
        showFeedback: true,
        showFixation: false,
        showResults: true,
        stimulusTrials: [
          {
            id: '5__png0',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/uT9zciGBfB5d7EXu7oyN8g.png',
            text: '5.png',
            value: 0,
            weight: null,
          },
          {
            id: 'image__1__png1',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/2F159Gsy66NdSgrdgsFAXL.png',
            text: 'image 1.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__2__png2',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/swBFCcF4DaGyXEusHY6PQK.png',
            text: 'IMAGE 2.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__png3',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/qgYVs1v9yVcE48B2psKuBP.png',
            text: 'IMAGE.png',
            value: 0,
            weight: null,
          },
          {
            id: 'iMAGE__3__png4',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/o68MKdhg2rJZ4sQG8UoEqL.png',
            text: 'iMAGE_3.png',
            value: 1,
            weight: null,
          },
          {
            id: '____________6__png5',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/tk8KsE56LsMW5vepDQrc5K.png',
            text: 'ШЬФПУ 6.png',
            value: 1,
            weight: null,
          },
        ],
        trialDuration: 3000,
      },
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e3204f-22d8-1858-d681-b9e600000000',
      inputType: 'Flanker',
      isAbleToMoveBack: false,
      isHidden: false,
      isSkippable: false,
      name: 'trial',
      question: '',
      timer: null,
    },
    {
      canBeReset: false,
      config: null,
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e3204f-22d8-1858-d681-b9e700000000',
      inputType: 'Message',
      isAbleToMoveBack: true,
      isHidden: false,
      isSkippable: false,
      name: 'trial2-instructions',
      question: '## Instructions\nPress the Next button to restart block.',
      timer: null,
    },
    {
      canBeReset: false,
      config: {
        blockType: 'practice',
        blocks: [
          {
            name: 'block 1',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 2',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 3',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 4',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
        ],
        buttons: [
          {
            image: null,
            text: 'HOME',
            value: 0,
          },
          {
            image: null,
            text: 'WILD',
            value: 1,
          },
        ],
        fixationDuration: 0,
        fixationScreen: {
          image: '',
          value: '',
        },
        isFirstPractice: false,
        isLastPractice: false,
        isLastTest: false,
        minimumAccuracy: 75,
        nextButton: 'OK',
        sampleSize: 1,
        samplingMethod: 'randomize-order',
        showFeedback: true,
        showFixation: false,
        showResults: true,
        stimulusTrials: [
          {
            id: '5__png0',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/uT9zciGBfB5d7EXu7oyN8g.png',
            text: '5.png',
            value: 0,
            weight: null,
          },
          {
            id: 'image__1__png1',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/2F159Gsy66NdSgrdgsFAXL.png',
            text: 'image 1.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__2__png2',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/swBFCcF4DaGyXEusHY6PQK.png',
            text: 'IMAGE 2.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__png3',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/qgYVs1v9yVcE48B2psKuBP.png',
            text: 'IMAGE.png',
            value: 0,
            weight: null,
          },
          {
            id: 'iMAGE__3__png4',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/o68MKdhg2rJZ4sQG8UoEqL.png',
            text: 'iMAGE_3.png',
            value: 1,
            weight: null,
          },
          {
            id: '____________6__png5',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/tk8KsE56LsMW5vepDQrc5K.png',
            text: 'ШЬФПУ 6.png',
            value: 1,
            weight: null,
          },
        ],
        trialDuration: 3000,
      },
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e3204f-22d8-1858-d681-b9e800000000',
      inputType: 'Flanker',
      isAbleToMoveBack: false,
      isHidden: false,
      isSkippable: false,
      name: 'trial2',
      question: '',
      timer: null,
    },
    {
      canBeReset: false,
      config: null,
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e3204f-22d8-1858-d681-b9e900000000',
      inputType: 'Message',
      isAbleToMoveBack: true,
      isHidden: false,
      isSkippable: false,
      name: 'trial3-instructions',
      question: '## Instructions\nPress the Next button to restart block.',
      timer: null,
    },
    {
      canBeReset: false,
      config: {
        blockType: 'practice',
        blocks: [
          {
            name: 'block 1',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 2',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 3',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 4',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
        ],
        buttons: [
          {
            image: null,
            text: 'HOME',
            value: 0,
          },
          {
            image: null,
            text: 'WILD',
            value: 1,
          },
        ],
        fixationDuration: 0,
        fixationScreen: {
          image: '',
          value: '',
        },
        isFirstPractice: false,
        isLastPractice: true,
        isLastTest: false,
        minimumAccuracy: 75,
        nextButton: 'OK',
        sampleSize: 1,
        samplingMethod: 'randomize-order',
        showFeedback: true,
        showFixation: false,
        showResults: true,
        stimulusTrials: [
          {
            id: '5__png0',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/uT9zciGBfB5d7EXu7oyN8g.png',
            text: '5.png',
            value: 0,
            weight: null,
          },
          {
            id: 'image__1__png1',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/2F159Gsy66NdSgrdgsFAXL.png',
            text: 'image 1.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__2__png2',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/swBFCcF4DaGyXEusHY6PQK.png',
            text: 'IMAGE 2.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__png3',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/qgYVs1v9yVcE48B2psKuBP.png',
            text: 'IMAGE.png',
            value: 0,
            weight: null,
          },
          {
            id: 'iMAGE__3__png4',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/o68MKdhg2rJZ4sQG8UoEqL.png',
            text: 'iMAGE_3.png',
            value: 1,
            weight: null,
          },
          {
            id: '____________6__png5',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/tk8KsE56LsMW5vepDQrc5K.png',
            text: 'ШЬФПУ 6.png',
            value: 1,
            weight: null,
          },
        ],
        trialDuration: 3000,
      },
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e32050-22d8-1858-d681-b9ea00000000',
      inputType: 'Flanker',
      isAbleToMoveBack: false,
      isHidden: false,
      isSkippable: false,
      name: 'trial3',
      question: '',
      timer: null,
    },
    {
      canBeReset: false,
      config: null,
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e32050-22d8-1858-d681-b9eb00000000',
      inputType: 'Message',
      isAbleToMoveBack: true,
      isHidden: false,
      isSkippable: false,
      name: 'test-instructions',
      question:
        '## Test Instructions\n\nGood job on the practice blocks.\nYou can now move on to the test blocks.\nYou will do the same task as in the practice, responding to the direction of the central arrow.\nYou will complete 3 blocks, each about 3-5 minutes long.\nYou will have  a short break in between these blocks\n',
      timer: null,
    },
    {
      canBeReset: false,
      config: {
        blockType: 'test',
        blocks: [
          {
            name: 'block 1',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 2',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 3',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 4',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
        ],
        buttons: [
          {
            image: null,
            text: 'HOME',
            value: 0,
          },
          {
            image: null,
            text: 'WILD',
            value: 1,
          },
        ],
        fixationDuration: 0,
        fixationScreen: {
          image: '',
          value: '',
        },
        isFirstPractice: false,
        isLastPractice: false,
        isLastTest: false,
        minimumAccuracy: null,
        nextButton: 'Continue',
        sampleSize: 1,
        samplingMethod: 'randomize-order',
        showFeedback: false,
        showFixation: false,
        showResults: true,
        stimulusTrials: [
          {
            id: '5__png0',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/uT9zciGBfB5d7EXu7oyN8g.png',
            text: '5.png',
            value: 0,
            weight: null,
          },
          {
            id: 'image__1__png1',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/2F159Gsy66NdSgrdgsFAXL.png',
            text: 'image 1.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__2__png2',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/swBFCcF4DaGyXEusHY6PQK.png',
            text: 'IMAGE 2.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__png3',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/qgYVs1v9yVcE48B2psKuBP.png',
            text: 'IMAGE.png',
            value: 0,
            weight: null,
          },
          {
            id: 'iMAGE__3__png4',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/o68MKdhg2rJZ4sQG8UoEqL.png',
            text: 'iMAGE_3.png',
            value: 1,
            weight: null,
          },
          {
            id: '____________6__png5',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/tk8KsE56LsMW5vepDQrc5K.png',
            text: 'ШЬФПУ 6.png',
            value: 1,
            weight: null,
          },
        ],
        trialDuration: 3000,
      },
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e32050-22d8-1858-d681-b9ec00000000',
      inputType: 'Flanker',
      isAbleToMoveBack: false,
      isHidden: false,
      isSkippable: false,
      name: 'test1',
      question: '',
      timer: null,
    },
    {
      canBeReset: false,
      config: null,
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e32051-22d8-1858-d681-b9ed00000000',
      inputType: 'Message',
      isAbleToMoveBack: true,
      isHidden: false,
      isSkippable: false,
      name: 'test2-instructions',
      question: '## Instructions\nPress the Next button to start next block.',
      timer: null,
    },
    {
      canBeReset: false,
      config: {
        blockType: 'test',
        blocks: [
          {
            name: 'block 1',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 2',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 3',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 4',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
        ],
        buttons: [
          {
            image: null,
            text: 'HOME',
            value: 0,
          },
          {
            image: null,
            text: 'WILD',
            value: 1,
          },
        ],
        fixationDuration: 0,
        fixationScreen: {
          image: '',
          value: '',
        },
        isFirstPractice: false,
        isLastPractice: false,
        isLastTest: false,
        minimumAccuracy: null,
        nextButton: 'Continue',
        sampleSize: 1,
        samplingMethod: 'randomize-order',
        showFeedback: false,
        showFixation: false,
        showResults: true,
        stimulusTrials: [
          {
            id: '5__png0',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/uT9zciGBfB5d7EXu7oyN8g.png',
            text: '5.png',
            value: 0,
            weight: null,
          },
          {
            id: 'image__1__png1',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/2F159Gsy66NdSgrdgsFAXL.png',
            text: 'image 1.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__2__png2',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/swBFCcF4DaGyXEusHY6PQK.png',
            text: 'IMAGE 2.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__png3',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/qgYVs1v9yVcE48B2psKuBP.png',
            text: 'IMAGE.png',
            value: 0,
            weight: null,
          },
          {
            id: 'iMAGE__3__png4',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/o68MKdhg2rJZ4sQG8UoEqL.png',
            text: 'iMAGE_3.png',
            value: 1,
            weight: null,
          },
          {
            id: '____________6__png5',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/tk8KsE56LsMW5vepDQrc5K.png',
            text: 'ШЬФПУ 6.png',
            value: 1,
            weight: null,
          },
        ],
        trialDuration: 3000,
      },
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e32051-22d8-1858-d681-b9ee00000000',
      inputType: 'Flanker',
      isAbleToMoveBack: false,
      isHidden: false,
      isSkippable: false,
      name: 'test2',
      question: '',
      timer: null,
    },
    {
      canBeReset: false,
      config: null,
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e32051-22d8-1858-d681-b9ef00000000',
      inputType: 'Message',
      isAbleToMoveBack: true,
      isHidden: false,
      isSkippable: false,
      name: 'test3-instructions',
      question: '## Instructions\nPress the Next button to start next block.',
      timer: null,
    },
    {
      canBeReset: false,
      config: {
        blockType: 'test',
        blocks: [
          {
            name: 'block 1',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 2',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 3',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
          {
            name: 'block 4',
            order: [
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
              '5__png0',
              'image__1__png1',
              'IMAGE__2__png2',
              'IMAGE__png3',
              'iMAGE__3__png4',
              '____________6__png5',
            ],
          },
        ],
        buttons: [
          {
            image: null,
            text: 'HOME',
            value: 0,
          },
          {
            image: null,
            text: 'WILD',
            value: 1,
          },
        ],
        fixationDuration: 0,
        fixationScreen: {
          image: '',
          value: '',
        },
        isFirstPractice: false,
        isLastPractice: false,
        isLastTest: true,
        minimumAccuracy: 2,
        nextButton: 'Continue',
        sampleSize: 1,
        samplingMethod: 'randomize-order',
        showFeedback: false,
        showFixation: false,
        showResults: true,
        stimulusTrials: [
          {
            id: '5__png0',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/uT9zciGBfB5d7EXu7oyN8g.png',
            text: '5.png',
            value: 0,
            weight: null,
          },
          {
            id: 'image__1__png1',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/2F159Gsy66NdSgrdgsFAXL.png',
            text: 'image 1.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__2__png2',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/swBFCcF4DaGyXEusHY6PQK.png',
            text: 'IMAGE 2.png',
            value: 1,
            weight: null,
          },
          {
            id: 'IMAGE__png3',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/qgYVs1v9yVcE48B2psKuBP.png',
            text: 'IMAGE.png',
            value: 0,
            weight: null,
          },
          {
            id: 'iMAGE__3__png4',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/o68MKdhg2rJZ4sQG8UoEqL.png',
            text: 'iMAGE_3.png',
            value: 1,
            weight: null,
          },
          {
            id: '____________6__png5',
            image:
              'https://mindlogger-applet-contents.s3.amazonaws.com/image/tk8KsE56LsMW5vepDQrc5K.png',
            text: 'ШЬФПУ 6.png',
            value: 1,
            weight: null,
          },
        ],
        trialDuration: 3000,
      },
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e32052-22d8-1858-d681-b9f000000000',
      inputType: 'Flanker',
      isAbleToMoveBack: false,
      isHidden: false,
      isSkippable: false,
      name: 'test3',
      order: 1,
      question: '',
      timer: null,
    },
  ],
  name: 'Simple & Choice Reaction Time Task Builder',
  order: 3,
  responseIsEditable: true,
  scoreSettings: [],
  scoresAndReports: {
    generateReport: false,
    reports: [],
    showScoreSummary: false,
  },
  showAllAtOnce: false,
  splashScreen: '',
} as ActivityDetails;
export const CSTInput = {
  id: '64e32047-22d8-1858-d681-b9da00000000',
  name: 'Stability_Task_gyro (custom)',
  description: 'This activity contains Stability tracker item.',
  splashScreen: '',
  image: '',
  showAllAtOnce: false,
  isSkippable: false,
  isReviewable: false,
  isHidden: false,
  responseIsEditable: true,
  order: 6,
  items: [
    {
      question:
        '# Hello!\nIn this task, you will see a disc that will drift either to the left or right side of the screen.\n Your job will be to keep the disc in the middle of the screen.\n If the disc is moving to the right, tilt your phone to the left to bring it back to the center.\n If the disc is moving to the left, tilt your phone to the right to bring the disc back to center.\n Do not let the disc touch the walls to the far left or right of the screen.\n There will be two phases to this task, a Challenge Phase, and a Focus Phase.',
      responseType: 'message',
      responseValues: null,
      config: { removeBackButton: false, timer: null },
      name: 'instructions',
      isHidden: false,
      conditionalLogic: null,
      allowEdit: true,
      id: '64e32059-22d8-1858-d681-ba0300000000',
    },
    {
      question:
        'This is the Challenge Phase.\n There will be 2 trials.\n Each trial will begin at an easy level, but it will become more difficult to keep the disc at the center of the screen.\n Eventually, you will lose control of the disc.\n When it hits a wall at the edge of the screen, the trial ends and the disc will be moved back to the center of the screen.\n Try to keep the disc away from the walls for as long as possible on each trial.',
      responseType: 'message',
      responseValues: null,
      config: { removeBackButton: false, timer: null },
      name: 'calibration-instructions',
      isHidden: false,
      conditionalLogic: null,
      allowEdit: true,
      id: '64e32059-22d8-1858-d681-ba0400000000',
    },
    {
      question: '',
      responseType: 'stabilityTracker',
      responseValues: null,
      config: {
        userInputType: 'gyroscope',
        phase: 'practice',
        trialsNumber: 2,
        durationMinutes: 1,
        lambdaSlope: 50,
        maxOffTargetTime: 10,
        numTestTrials: 10,
        taskMode: 'pseudo_stair',
        trackingDims: 2,
        showScore: true,
        basisFunc: 'zeros_1d',
        noiseLevel: 0,
        taskLoopRate: 0.0167,
        cyclesPerMin: 2,
        oobDuration: 0.2,
        initialLambda: 0.075,
        showPreview: true,
        numPreviewStim: 0,
        previewStepGap: 100,
        dimensionCount: 1,
        maxRad: 0.26167,
      },
      name: 'calibration-phase',
      isHidden: false,
      conditionalLogic: null,
      allowEdit: true,
      id: '64e3205a-22d8-1858-d681-ba0500000000',
    },
    {
      question:
        'This is the Focus Phase.\n This phase will last 1 minutes.\n The trial will begin at an easy level, and will increase to a level that should not be very difficult.\n Your task will be to focus on keeping the disc in the center of the screen, without letting it drift off center.\n If you lose control of the disc and it hits a wall, the disc will be moved back to the center of the screen and the task will continue.',
      responseType: 'message',
      responseValues: null,
      config: { removeBackButton: false, timer: null },
      name: 'continuous-instructions',
      isHidden: false,
      conditionalLogic: null,
      allowEdit: true,
      id: '64e3205a-22d8-1858-d681-ba0600000000',
    },
    {
      question: '',
      responseType: 'stabilityTracker',
      responseValues: null,
      config: {
        userInputType: 'gyroscope',
        phase: 'test',
        trialsNumber: 0,
        durationMinutes: 1,
        lambdaSlope: 50,
      },
      name: 'continuous-phase',
      isHidden: false,
      conditionalLogic: null,
      id: '64e3205b-22d8-1858-d681-ba0700000000',
      order: 1,
      timer: null,
    },
  ] as StabilityTrackerItemDto[],
  scoresAndReports: {
    generateReport: false,
    showScoreSummary: false,
    reports: [],
  },
};

export const CSTOutput = {
  description: 'This activity contains Stability tracker item.',
  hasSummary: false,
  id: '64e32047-22d8-1858-d681-b9da00000000',
  image: '',
  isHidden: false,
  isReviewable: false,
  isSkippable: false,
  items: [
    {
      canBeReset: false,
      config: null,
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e32059-22d8-1858-d681-ba0300000000',
      inputType: 'Message',
      isAbleToMoveBack: true,
      isHidden: false,
      isSkippable: false,
      name: 'instructions',
      question:
        '# Hello!\nIn this task, you will see a disc that will drift either to the left or right side of the screen.\n Your job will be to keep the disc in the middle of the screen.\n If the disc is moving to the right, tilt your phone to the left to bring it back to the center.\n If the disc is moving to the left, tilt your phone to the right to bring the disc back to center.\n Do not let the disc touch the walls to the far left or right of the screen.\n There will be two phases to this task, a Challenge Phase, and a Focus Phase.',
      timer: null,
    },
    {
      canBeReset: false,
      config: null,
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e32059-22d8-1858-d681-ba0400000000',
      inputType: 'Message',
      isAbleToMoveBack: true,
      isHidden: false,
      isSkippable: false,
      name: 'calibration-instructions',
      question:
        'This is the Challenge Phase.\n There will be 2 trials.\n Each trial will begin at an easy level, but it will become more difficult to keep the disc at the center of the screen.\n Eventually, you will lose control of the disc.\n When it hits a wall at the edge of the screen, the trial ends and the disc will be moved back to the center of the screen.\n Try to keep the disc away from the walls for as long as possible on each trial.',
      timer: null,
    },
    {
      canBeReset: true,
      config: {
        durationMinutes: 1,
        lambdaSlope: 50,
        phase: 'practice',
        trialsNumber: 2,
        userInputType: 'gyroscope',
      },
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e3205a-22d8-1858-d681-ba0500000000',
      inputType: 'StabilityTracker',
      isAbleToMoveBack: true,
      isHidden: false,
      isSkippable: false,
      name: 'calibration-phase',
      question: '',
      timer: null,
    },
    {
      canBeReset: false,
      config: null,
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e3205a-22d8-1858-d681-ba0600000000',
      inputType: 'Message',
      isAbleToMoveBack: true,
      isHidden: false,
      isSkippable: false,
      name: 'continuous-instructions',
      question:
        'This is the Focus Phase.\n This phase will last 1 minutes.\n The trial will begin at an easy level, and will increase to a level that should not be very difficult.\n Your task will be to focus on keeping the disc in the center of the screen, without letting it drift off center.\n If you lose control of the disc and it hits a wall, the disc will be moved back to the center of the screen and the task will continue.',
      timer: null,
    },
    {
      canBeReset: true,
      config: {
        durationMinutes: 1,
        lambdaSlope: 50,
        phase: 'test',
        trialsNumber: 0,
        userInputType: 'gyroscope',
      },
      hasAlert: false,
      hasScore: false,
      hasTextResponse: false,
      hasTopNavigation: false,
      id: '64e3205b-22d8-1858-d681-ba0700000000',
      inputType: 'StabilityTracker',
      isAbleToMoveBack: true,
      isHidden: false,
      isSkippable: false,
      name: 'continuous-phase',
      order: 1,
      question: '',
      timer: null,
    },
  ],
  name: 'Stability_Task_gyro (custom)',
  order: 6,
  responseIsEditable: true,
  scoreSettings: [],
  scoresAndReports: {
    generateReport: false,
    reports: [],
    showScoreSummary: false,
  },
  showAllAtOnce: false,
  splashScreen: '',
} as ActivityDetails;
