desc 'Android: Increment versionCode and set versionName to package.json version.'
package = load_json(json_path: "./package.json")

private_lane :increment_version_android do |options|
  gradle_file = './android/app/build.gradle'

  increment_version_code(
    gradle_file_path: gradle_file,
  )

  increment_version_name(
    gradle_file_path: gradle_file,
    version_name: package['version']
  )
end


desc 'iOS: Increment build number and set the version to package.json version.'
private_lane :increment_version_ios do |options|
package = load_json(json_path: "./package.json")
  xcodeproj_path = 'ios/MindloggerMobile.xcodeproj'

  increment_build_number_in_xcodeproj(
    xcodeproj: xcodeproj_path,
  )

  increment_version_number_in_xcodeproj(
    xcodeproj: xcodeproj_path,
    version_number: package['version']
  )
end

desc 'Automatically add commit message including build number.'
private_lane :commit_version do |options|
  package = load_json(json_path: "./package.json")
  xcodeproj_path = 'ios/MindloggerMobile.xcodeproj'
  version_number = package['version']
  build_number = get_build_number(xcodeproj: xcodeproj_path)

  git_commit(path: [
    './android/app/build.gradle',
    './ios/MindloggerMobile.xcodeproj/project.pbxproj'
    ], message: "chore: bump version #{version_number} (#{build_number})"
  )
end

desc 'Bump build numbers, and set the version to match the pacakage.json version.'
lane :bump_version do |options|
  increment_version_android
  increment_version_ios
  commit_version
end