import { IS_ANDROID, IS_IOS } from '@shared/lib';

const ONE_MINUTE = 60000;

const MAX_SCHEDULED_NOTIFICATION_SIZE_ANDROID = 50;
const MAX_SCHEDULED_NOTIFICATIONS_SIZE_IOS = 64;

export const ANDROID_DEFAULT_CHANNEL_ID = 'MindLoggerChannelId';

export const SYSTEM_RESCHEDULING_NOTIFICATION_ID = 'system_trigger_for_rescheduling';

export const SYSTEM_RESERVED_CAPACITY = IS_IOS ? 1 : 0;

export const MAX_SCHEDULED_NOTIFICATIONS_SIZE =
  (IS_ANDROID ? MAX_SCHEDULED_NOTIFICATION_SIZE_ANDROID : MAX_SCHEDULED_NOTIFICATIONS_SIZE_IOS) -
  SYSTEM_RESERVED_CAPACITY;

export const SYSTEM_NOTIFICATION_DELAY = ONE_MINUTE * 30;
