name: Build and Deploy to UAT

on:
  release: 
    types:
      - prereleased
#  push:
#    tags:
#      - "*-rc[0-9]+"
  workflow_dispatch:
    inputs:
      target-ref:
        description: The RC tag to use
        required: true
        type: string

concurrency:
  cancel-in-progress: true
  group: mobile-build-deploy-uat

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  ref:
    name: Get target ref
    runs-on: ubuntu-latest
    outputs:
      target-ref: ${{ steps.ref.outputs.ref }}
    steps:
      - id: ref
        name: Select Ref
        # github.refname
        run: |
          TARGET_REF="${{ github.event.inputs.target-ref }}"
          # Use shell parameter expansion to provide a default value if input is unset or empty
          # github.ref_name will be used if the input is not provided or empty
          # Remove "refs/heads/" or "refs/tags/" if present in github.ref_name
          TARGET_REF=${TARGET_REF:-$(echo "${{ github.event.release.tag_name }}" | sed 's/refs\/heads\///g' | sed 's/refs\/tags\///g')} 

          echo "Target reference: $TARGET_REF"
          echo "ref=$TARGET_REF" >> $GITHUB_OUTPUT

  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: ref
    steps:
      - name: Trigger Bitrise Build
        run: |      
          curl https://app.bitrise.io/app/${{ secrets.BITRISE_APP_SLUG }}/build/start.json -L \
            --data '{"build_params":{"pipeline_id":"start_uat","tag":"${{ needs.ref.outputs.target-ref }}"},"hook_info":{"build_trigger_token":"${{ secrets.BITRISE_BUILD_TOKEN }}","type":"bitrise"},"triggered_by":"gha"}' \
            -H "Content-Type: application/json"
          
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::917902836630:role/ssm-versions-oidc-github-role
          role-session-name: OIDC-GHA-session-version
          aws-region: us-east-1
      - name: Store version in SSM
        run: |
          aws ssm put-parameter \
                  --name "/curious/app/mobile/uat/version" \
                  --value "${{ needs.ref.outputs.target-ref }}" \
                  --type "String" \
                  --overwrite

  notify:
    name: Notifications
    needs: [ ref, build-deploy ]
    uses: ./.github/workflows/_notify-jira.yaml
    with:
      env-name: uat
      git-tag: ${{ needs.ref.outputs.target-ref }}
    secrets:
      devops-repo-key: ${{ secrets.DEVOPS_REPO_KEY }}
      jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
      github-pat: ${{ secrets.DEVOPS_GITHUB_TOKEN }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK_RELEASE_COMMUNICATIONS }}
